import { Codes } from "./Codes";

export const basho = new Codes(
  [
    { code: 0, kol: "00", jrdb: "08", naiyou: "京都" },
    { code: 1, kol: "01", jrdb: "09", naiyou: "阪神" },
    { code: 2, kol: "02", jrdb: "07", naiyou: "中京" },
    { code: 3, kol: "03", jrdb: "10", naiyou: "小倉" },
    { code: 4, kol: "04", jrdb: "05", naiyou: "東京" },
    { code: 5, kol: "05", jrdb: "06", naiyou: "中山" },
    { code: 6, kol: "06", jrdb: "03", naiyou: "福島" },
    { code: 7, kol: "07", jrdb: "04", naiyou: "新潟" },
    { code: 8, kol: "08", jrdb: "01", naiyou: "札幌" },
    { code: 9, kol: "09", jrdb: "02", naiyou: "函館" },
    { code: 10, kol: "10", jrdb: "35", naiyou: "大井" },
    { code: 11, kol: "11", jrdb: "36", naiyou: "川崎" },
    { code: 12, kol: "12", jrdb: "34", naiyou: "船橋" },
    { code: 13, kol: "13", jrdb: "33", naiyou: "浦和" },
    { code: 14, kol: "14", naiyou: "岩見" },
    { code: 15, kol: "15", jrdb: "21", naiyou: "旭川" },
    { code: 16, kol: "16", naiyou: "帯広" },
    { code: 17, kol: "17", naiyou: "野田" },
    { code: 18, kol: "18", naiyou: "北見" },
    { code: 19, kol: "19", jrdb: "38", naiyou: "笠松" },
    { code: 20, kol: "20", jrdb: "37", naiyou: "金沢" },
    { code: 21, kol: "21", jrdb: "47", naiyou: "荒尾" },
    { code: 22, kol: "22", jrdb: "31", naiyou: "宇都" },
    { code: 23, kol: "23", jrdb: "46", naiyou: "佐賀" },
    { code: 24, kol: "24", jrdb: "48", naiyou: "中津" },
    { code: 25, kol: "25", jrdb: "32", naiyou: "高崎" },
    { code: 26, kol: "26", jrdb: "45", naiyou: "高知" },
    { code: 27, kol: "27", jrdb: "30", naiyou: "足利" },
    { code: 28, kol: "28", jrdb: "27", naiyou: "上山" },
    { code: 29, kol: "29", jrdb: "26", naiyou: "水沢" },
    { code: 30, kol: "30", jrdb: "29", naiyou: "三条" },
    { code: 31, kol: "31", naiyou: "紀井" },
    { code: 32, kol: "32", jrdb: "43", naiyou: "益田" },
    { code: 33, kol: "33", jrdb: "25", naiyou: "盛岡" },
    { code: 34, kol: "34", jrdb: "39", naiyou: "名古" },
    { code: 35, kol: "35", jrdb: "22", naiyou: "札幌(地方)" },
    { code: 36, kol: "36", jrdb: "24", naiyou: "函館(地方)" },
    { code: 37, kol: "37", jrdb: "41", naiyou: "園田" },
    { code: 38, kol: "38", jrdb: "44", naiyou: "福山" },
    { code: 39, kol: "39", jrdb: "42", naiyou: "姫路" },
    { code: 40, kol: "40", jrdb: "40", naiyou: "中京(地方)" },
    { code: 41, kol: "41", jrdb: "28", naiyou: "新潟(地方)" },
    { code: 42, kol: "42", jrdb: "23", naiyou: "門別" },
    { code: 43, kol: "43", naiyou: "弥富" },
    { code: 44, kol: "44", naiyou: "小林" },
    { code: 45, kol: "45", naiyou: "西脇" },
    { code: 46, kol: "46", naiyou: "境町" },
    { code: 47, kol: "47", naiyou: "小向" },
    { code: 50, kol: "50", naiyou: "栗東" },
    { code: 51, kol: "51", naiyou: "美浦南" },
    { code: 52, kol: "52", naiyou: "美浦北" },
    { code: 53, kol: "53", naiyou: "白井" },
    { code: 54, kol: "54", naiyou: "道営" },
    { code: 55, kol: "55", naiyou: "岩手" },
    { code: 56, kol: "56", naiyou: "岩見" },
    { code: 57, kol: "57", naiyou: "旭川" },
    { code: 58, kol: "58", naiyou: "帯広" },
    { code: 59, kol: "59", naiyou: "北見" },
    { code: 60, kol: "60", jrdb: "71", naiyou: "香港" },
    { code: 61, kol: "61", jrdb: "66", naiyou: "米国" },
    { code: 62, kol: "62", jrdb: "61", naiyou: "英国" },
    { code: 63, kol: "63", jrdb: "63", naiyou: "仏国" },
    { code: 64, kol: "64", jrdb: "62", naiyou: "愛国" },
    { code: 65, kol: "65", jrdb: "68", naiyou: "UAE" },
    { code: 66, kol: "66", jrdb: "67", naiyou: "加国" },
    { code: 67, kol: "67", jrdb: "64", naiyou: "伊国" },
    { code: 68, kol: "68", jrdb: "65", naiyou: "独国" },
    { code: 69, kol: "69", jrdb: "69", naiyou: "豪州" },
    { code: 70, kol: "70", naiyou: "西独" },
    { code: 71, kol: "71", jrdb: "70", naiyou: "新国" },
    { code: 72, kol: "72", jrdb: "72", naiyou: "チリ" },
    { code: 73, kol: "73", naiyou: "亜国" },
    { code: 74, kol: "74", naiyou: "伯国" },
    { code: 75, kol: "75", naiyou: "新嘉坡" },
    { code: 76, kol: "76", naiyou: "瑞典" },
    { code: 77, kol: "77", naiyou: "西班牙" },
    { code: 78, kol: "78", naiyou: "瑞西" },
    { code: 79, kol: "79", naiyou: "白耳義" },
    { code: 80, kol: "80", jrdb: "75", naiyou: "マカオ" },
    { code: 81, kol: "81", naiyou: "墺国" },
    { code: 82, kol: "82", naiyou: "トルコ" },
    { code: 83, kol: "83", naiyou: "カタール" },
    { code: 85, kol: "85", naiyou: "韓国" },
    { code: 86, kol: "86", naiyou: "ソウル" },
    { code: 87, kol: "87", naiyou: "プサン" },
    { code: 88, kol: "88", naiyou: "ペルー" },
    { code: 89, kol: "89", naiyou: "サウジ" },
    { code: 90, kol: "90", naiyou: "兵庫" },
    { code: 91, kol: "91", naiyou: "栃木" },
    { code: 92, kol: "92", naiyou: "バーレ" },
    { code: 94, kol: "94", naiyou: "南ア" },
    { code: 96, jrdb: "76", naiyou: "墺国" },
    { code: 97, jrdb: "74", naiyou: "瑞国" },
    { code: 98, jrdb: "73", naiyou: "星国" },
    { code: 99, kol: "99", naiyou: "北海" },
  ]
);

export const touzaiBetsu = new Codes(
  [
    { code: 0, kol: "0", naiyou: "西" },
    { code: 1, kol: "1", naiyou: "東" },
    { code: 2, kol: "2", naiyou: "招待" }
  ]
);