import { Codes } from "./Codes";

export const blinker = new Codes(
  [
    { code: 1, jrdb: "1", naiyou: "初装着" },
    { code: 2, jrdb: "2", naiyou: "再装着" },
    { code: 3, kol: "1", jrdb: "3", naiyou: "ブリンカー" }
  ]
);

export const minaraiKubun = new Codes(
  [
    { code: 1, kol: "1", jrdb: "1", naiyou: "1kg減", tanshuku: "☆" },
    { code: 2, kol: "2", jrdb: "2", naiyou: "2kg減", tanshuku: "△" },
    { code: 3, kol: "3", jrdb: "3", naiyou: "3kg減", tanshuku: "▲" }
  ]
);

export const norikawari = new Codes(
  [
    { code: 1, kol: "1", naiyou: "乗り替り", tanshuku: "乗Ï替" }
  ]
);

export const yosou = new Codes(
  [
    { code: 1, kol: "0", jrdb: "1", naiyou: "◎" },
    { code: 2, kol: "1", jrdb: "2", naiyou: "○" },
    { code: 3, kol: "2", jrdb: "3", naiyou: "▲" },
    { code: 5, kol: "3", jrdb: /5|6/, naiyou: "△" },
    { code: 6, kol: "4", jrdb: "4", naiyou: "×" }
  ]
);

export const chakujunFuka = new Codes(
  [
    { code: 1, kol: "31", naiyou: "落馬" },
    { code: 2, kol: "32", jrdb: "4", naiyou: "失格" },
    { code: 3, kol: "33", jrdb: "3", naiyou: "中止" },
    { code: 4, kol: "34", jrdb: "1", naiyou: "取消" },
    { code: 5, kol: "35", jrdb: "2", naiyou: "除外" },
    { code: 6, kol: "36", jrdb: "5", naiyou: "降着" },
    { code: 7, kol: "37", naiyou: "繰上" },
    { code: 10, kol: "40", naiyou: "不利" },
    { code: 11, jrdb: "6", naiyou: "再騎乗" }
  ]
);

export const torikeshiShubetsu = new Codes(
  [
    { code: 1, kol: "1", jrdb: "1", naiyou: "出走取消" },
    { code: 2, kol: "2", naiyou: "出走除外" },
    { code: 3, kol: "3", naiyou: "競走除外" },
    { code: 4, kol: "4", naiyou: "競走中止" },
    { code: 5, kol: "5", naiyou: "放馬" },
    { code: 6, kol: "6", naiyou: "発走除外" }
  ]
);

export const recordNinshiki = new Codes(
  [
    { code: 1, kol: "1", naiyou: "レコードÏ" }
  ]
);

export const chakura2 = new Codes(
  [
    { code: 0, kol: "0", naiyou: "ハナ" },
    { code: 1, kol: "1", naiyou: "アタマ" },
    { code: 2, kol: "2", naiyou: "クビ" },
    { code: 3, kol: "3", naiyou: "1/2" },
    { code: 4, kol: "4", naiyou: "1/4" },
    { code: 5, kol: "5", naiyou: "3/4" },
    { code: 7, kol: "7", naiyou: "大差" },
    { code: 8, kol: "8", naiyou: "同着" }
  ]
);

export const kyuuyouRiyuuCode = new Codes(
  [
    { code: 1, jrdb: "01", naiyou: "放牧" },
    { code: 2, jrdb: "02", naiyou: "放牧(故障、骨折等)" },
    { code: 3, jrdb: "03", naiyou: "放牧(不安、ソエ等)" },
    { code: 4, jrdb: "04", naiyou: "放牧(病気)" },
    { code: 5, jrdb: "05", naiyou: "放牧(再審査)" },
    { code: 6, jrdb: "06", naiyou: "放牧(出走停止)" },
    { code: 7, jrdb: "07", naiyou: "放牧(手術)" },
    { code: 11, jrdb: "11", naiyou: "調整" },
    { code: 12, jrdb: "12", naiyou: "調整(故障、骨折等)" },
    { code: 13, jrdb: "13", naiyou: "調整(不安、ソエ等)" },
    { code: 14, jrdb: "14", naiyou: "調整(病気)" },
    {
      kol: (str) => {
        if (!str) {
          return null;
        } else if (/放牧/.test(str)) {
          if (/故障|骨折|屈腱炎/.test(str)) return 2;
          if (/手術|去勢/.test(str)) return 7;
          if (/出走停止/.test(str)) return 6;
          if (/再審査/.test(str)) return 5;
          if (/病|血|熱|蕁麻疹|鼻|肺|胃|腸|フレグモーネ/.test(str)) return 4;
          if (/不安|骨|節|股|蹄|肩|爪|トモ|ソエ|捻挫|傷|蟻洞|跛行/.test(str)) return 3;
          return 1;
        } else {
          if (/故障|骨折|屈腱炎/.test(str)) return 12;
          if (/病|血|熱|蕁麻疹|鼻|肺|胃|腸|フレグモーネ/.test(str)) return 14;
          if (/不安|骨|節|股|蹄|肩|爪|トモ|ソエ|捻挫|傷|蟻洞|跛行/.test(str)) return 13;
          return 11;
        }
      }
    }
  ]
);
export enum Ichi {
  Saiuchi = 0,
  Uchi,
  Naka,
  Soto,
  Ohsoto
}

export const ichi = new Codes(
  [
    { code: Ichi.Saiuchi, kol: "0", jrdb: "1", naiyou: "最内" },
    { code: Ichi.Uchi, kol: "1", jrdb: "2", naiyou: "内" },
    { code: Ichi.Naka, kol: "2", jrdb: "3", naiyou: "中" },
    { code: Ichi.Soto, kol: "3", jrdb: "4", naiyou: "外" },
    { code: Ichi.Ohsoto, kol: "4", jrdb: "5", naiyou: "大外" }
  ]
);

export const joushoudo = new Codes(
  [
    { code: 1, jrdb: "1", naiyou: "AA" },
    { code: 2, jrdb: "2", naiyou: "A" },
    { code: 3, jrdb: "3", naiyou: "B" },
    { code: 4, jrdb: "4", naiyou: "C" },
    { code: 5, jrdb: "5", naiyou: "D" }
  ]
);

export const hyouka = new Codes(
  [
    { code: 1, jrdb: "1", naiyou: "◎" },
    { code: 2, jrdb: "2", naiyou: "○" },
    { code: 3, jrdb: "3", naiyou: "△" },
  ]
);

export const classCode = new Codes(
  [
    { code: 1, jrdb: "01", naiyou: "芝G1" },
    { code: 2, jrdb: "02", naiyou: "芝G2" },
    { code: 3, jrdb: "03", naiyou: "芝G3" },
    { code: 4, jrdb: "04", naiyou: "芝OP A" },
    { code: 5, jrdb: "05", naiyou: "芝OP B" },
    { code: 6, jrdb: "06", naiyou: "芝OP C" },
    { code: 7, jrdb: "07", naiyou: "芝1600万A" },
    { code: 8, jrdb: "08", naiyou: "芝1600万B" },
    { code: 9, jrdb: "09", naiyou: "芝1600万C" },
    { code: 10, jrdb: "10", naiyou: "芝1000万A" },
    { code: 11, jrdb: "11", naiyou: "芝1000万B" },
    { code: 12, jrdb: "12", naiyou: "芝1000万C" },
    { code: 13, jrdb: "13", naiyou: "芝500万A" },
    { code: 14, jrdb: "14", naiyou: "芝500万B" },
    { code: 15, jrdb: "15", naiyou: "芝500万C" },
    { code: 16, jrdb: "16", naiyou: "芝未A" },
    { code: 17, jrdb: "17", naiyou: "芝未B" },
    { code: 18, jrdb: "18", naiyou: "芝未C" },
    { code: 21, jrdb: "21", naiyou: "ダG1" },
    { code: 22, jrdb: "22", naiyou: "ダG2" },
    { code: 23, jrdb: "23", naiyou: "ダG3" },
    { code: 24, jrdb: "24", naiyou: "ダOP A" },
    { code: 25, jrdb: "25", naiyou: "ダOP B" },
    { code: 26, jrdb: "26", naiyou: "ダOP C" },
    { code: 27, jrdb: "27", naiyou: "ダ1600万A" },
    { code: 28, jrdb: "28", naiyou: "ダ1600万B" },
    { code: 29, jrdb: "29", naiyou: "ダ1600万C" },
    { code: 30, jrdb: "30", naiyou: "ダ1000万A" },
    { code: 31, jrdb: "31", naiyou: "ダ1000万B" },
    { code: 32, jrdb: "32", naiyou: "ダ1000万C" },
    { code: 33, jrdb: "33", naiyou: "ダ500万A" },
    { code: 34, jrdb: "34", naiyou: "ダ500万B" },
    { code: 35, jrdb: "35", naiyou: "ダ500万C" },
    { code: 36, jrdb: "36", naiyou: "ダ未A" },
    { code: 37, jrdb: "37", naiyou: "ダ未B" },
    { code: 38, jrdb: "38", naiyou: "ダ未C" },
    { code: 51, jrdb: "51", naiyou: "障G1" },
    { code: 52, jrdb: "52", naiyou: "障G2" },
    { code: 53, jrdb: "53", naiyou: "障G3" },
    { code: 54, jrdb: "54", naiyou: "障OP A" },
    { code: 55, jrdb: "55", naiyou: "障OP B" },
    { code: 56, jrdb: "56", naiyou: "障OP C" },
    { code: 57, jrdb: "57", naiyou: "障500万A" },
    { code: 58, jrdb: "58", naiyou: "障500万B" },
    { code: 59, jrdb: "59", naiyou: "障500万C" },
    { code: 60, jrdb: "60", naiyou: "障未A" },
    { code: 61, jrdb: "61", naiyou: "障未B" },
    { code: 62, jrdb: "62", naiyou: "障未C" },
  ]
);

export const bataiCode = new Codes(
  [
    { code: 1, jrdb: "1", naiyou: "太い" },
    { code: 2, jrdb: "2", naiyou: "余裕" },
    { code: 3, jrdb: "3", naiyou: "良い" },
    { code: 4, jrdb: "4", naiyou: "普通" },
    { code: 5, jrdb: "5", naiyou: "細い" },
    { code: 6, jrdb: "6", naiyou: "張り" },
  ]
);

export const kehaiCode = new Codes(
  [
    { code: 1, jrdb: "1", naiyou: "状態良" },
    { code: 2, jrdb: "2", naiyou: "平凡" },
    { code: 3, jrdb: "3", naiyou: "不安定" },
    { code: 4, jrdb: "4", naiyou: "イレ込" },
    { code: 5, jrdb: "5", naiyou: "気合良" },
    { code: 6, jrdb: "6", naiyou: "気不足" },
  ]
);

export const kyakushitsu = new Codes(
  [
    { code: 1, jrdb: "1", naiyou: "逃げ" },
    { code: 2, jrdb: "2", naiyou: "先行" },
    { code: 3, jrdb: "3", naiyou: "差し" },
    { code: 4, jrdb: "4", naiyou: "追込" },
    { code: 5, jrdb: "5", naiyou: "好位差し" },
    { code: 6, jrdb: "6", naiyou: "自在" },
  ]
);

export const tokki = new Codes(
  [
    { code: 33, jrdb: "033", naiyou: "口向き悪い", tanshuku: "口向悪い" },
    { code: 34, jrdb: "034", naiyou: "放馬", tanshuku: "放馬" },
    { code: 35, jrdb: "035", naiyou: "落鉄", tanshuku: "R中落鉄" },
    { code: 37, jrdb: "037", naiyou: "揉まれ弱い", tanshuku: "揉れ弱い" },
    { code: 38, jrdb: "038", naiyou: "芝向き", tanshuku: "芝向き" },
    { code: 39, jrdb: "039", naiyou: "ダート向き", tanshuku: "ダ向き" },
    { code: 40, jrdb: "040", naiyou: "心房細動", tanshuku: "心房細動" },
    { code: 41, jrdb: "041", naiyou: "喉鳴り", tanshuku: "喉鳴り" },
    { code: 42, jrdb: "042", naiyou: "熱発", tanshuku: "熱発" },
    { code: 43, jrdb: "043", naiyou: "鼻出血", tanshuku: "鼻出血" },
    { code: 44, jrdb: "044", naiyou: "ソエ", tanshuku: "ソエ" },
    { code: 45, jrdb: "045", naiyou: "恐がり", tanshuku: "恐がり" },
    { code: 46, jrdb: "046", naiyou: "脚腫れる", tanshuku: "脚腫れる" },
    { code: 47, jrdb: "047", naiyou: "コズミ", tanshuku: "コズミ" },
    { code: 48, jrdb: "048", naiyou: "腰フラ", tanshuku: "腰フラ" },
    { code: 49, jrdb: "049", naiyou: "気悪", tanshuku: "気悪" },
    { code: 50, jrdb: "050", naiyou: "素直", tanshuku: "素直" },
    { code: 51, jrdb: "051", naiyou: "根性有り", tanshuku: "根性有り" },
    { code: 52, jrdb: "052", naiyou: "ハミ悪", tanshuku: "ハミ悪" },
    { code: 53, jrdb: "053", naiyou: "頭高い(レース中)", tanshuku: "R中頭高" },
    { code: 54, jrdb: "054", naiyou: "内枠×", tanshuku: "内枠×" },
    { code: 55, jrdb: "055", naiyou: "外枠×", tanshuku: "外枠×" },
    { code: 56, jrdb: "056", naiyou: "内枠○", tanshuku: "内枠○" },
    { code: 57, jrdb: "057", naiyou: "外枠○", tanshuku: "外枠○" },
    { code: 58, jrdb: "058", naiyou: "スタート良い", tanshuku: "スタ良い" },
    { code: 59, jrdb: "059", naiyou: "スタート悪い", tanshuku: "スタ悪い" },
    { code: 60, jrdb: "060", naiyou: "内もたれ", tanshuku: "内もたれ" },
    { code: 61, jrdb: "061", naiyou: "外もたれ", tanshuku: "外もたれ" },
    { code: 62, jrdb: "062", naiyou: "ハナ条件", tanshuku: "ハナ条件" },
    { code: 63, jrdb: "063", naiyou: "ダ重い○", tanshuku: "ダ重い○" },
    { code: 64, jrdb: "064", naiyou: "ダ重い×", tanshuku: "ダ重い×" },
    { code: 65, jrdb: "065", naiyou: "ダ軽い○", tanshuku: "ダ軽い○" },
    { code: 66, jrdb: "066", naiyou: "ダ軽い×", tanshuku: "ダ軽い×" },
    { code: 67, jrdb: "067", naiyou: "ダ少し掛○", tanshuku: "ダ少掛○" },
    { code: 68, jrdb: "068", naiyou: "ダ少し掛×", tanshuku: "ダ少掛×" },
    { code: 69, jrdb: "069", naiyou: "芝重い○", tanshuku: "芝重い○" },
    { code: 70, jrdb: "070", naiyou: "芝重い×", tanshuku: "芝重い×" },
    { code: 71, jrdb: "071", naiyou: "芝軽い○", tanshuku: "芝軽い○" },
    { code: 72, jrdb: "072", naiyou: "芝軽い×", tanshuku: "芝軽い×" },
    { code: 73, jrdb: "073", naiyou: "芝滑る○", tanshuku: "芝滑る○" },
    { code: 74, jrdb: "074", naiyou: "芝滑る×", tanshuku: "芝滑る×" },
    { code: 75, jrdb: "075", naiyou: "芝少し掛○", tanshuku: "芝少掛○" },
    { code: 76, jrdb: "076", naiyou: "芝少し掛×", tanshuku: "芝少掛×" },
    { code: 77, jrdb: "077", naiyou: "雨嫌い", tanshuku: "雨嫌い" },
    { code: 78, jrdb: "078", naiyou: "ズブイ", tanshuku: "ズブイ" },
    { code: 79, jrdb: "079", naiyou: "シブトイ", tanshuku: "シブトイ" },
    { code: 80, jrdb: "080", naiyou: "折り合い○", tanshuku: "折合○" },
    { code: 81, jrdb: "081", naiyou: "折り合い×", tanshuku: "折合×" },
    { code: 82, jrdb: "082", naiyou: "先行力○", tanshuku: "先行力○" },
    { code: 83, jrdb: "083", naiyou: "先行力×", tanshuku: "先行力×" },
    { code: 84, jrdb: "084", naiyou: "瞬発力○", tanshuku: "瞬発力○" },
    { code: 85, jrdb: "085", naiyou: "瞬発力×", tanshuku: "瞬発力×" },
    { code: 86, jrdb: "086", naiyou: "調教良い", tanshuku: "調教良い" },
    { code: 87, jrdb: "087", naiyou: "大トビ", tanshuku: "大トビ" },
    { code: 88, jrdb: "088", naiyou: "調教出来ず", tanshuku: "調教ダメ" },
    { code: 89, jrdb: "089", naiyou: "右回り○", tanshuku: "右回り○" },
    { code: 90, jrdb: "090", naiyou: "左回り○", tanshuku: "左回り○" },
    { code: 91, jrdb: "091", naiyou: "トモ甘い", tanshuku: "トモ甘い" },
    { code: 92, jrdb: "092", naiyou: "馬込み×", tanshuku: "馬込み×" },
    { code: 93, jrdb: "093", naiyou: "骨膜炎", tanshuku: "骨膜炎" },
    { code: 94, jrdb: "094", naiyou: "裂蹄", tanshuku: "裂蹄" },
    { code: 95, jrdb: "095", naiyou: "ゴトゴト", tanshuku: "ゴトゴト" },
    { code: 96, jrdb: "096", naiyou: "物見", tanshuku: "物見" },
    { code: 97, jrdb: "097", naiyou: "鐙外れ", tanshuku: "鐙外れ" },
    { code: 98, jrdb: "098", naiyou: "ソラ使う", tanshuku: "ソラ使う" },
    { code: 99, jrdb: "099", naiyou: "左回り×", tanshuku: "左回り×" },
    { code: 100, jrdb: "100", naiyou: "右回り×", tanshuku: "右回り×" },
    { code: 101, jrdb: "101", naiyou: "ダート×", tanshuku: "ダート×" },
    { code: 102, jrdb: "102", naiyou: "芝×", tanshuku: "芝×" },
    { code: 103, jrdb: "103", naiyou: "左モタレ", tanshuku: "左モタレ" },
    { code: 104, jrdb: "104", naiyou: "右モタレ", tanshuku: "右モタレ" },
    { code: 105, jrdb: "105", naiyou: "センスある", tanshuku: "センス○" },
    { code: 106, jrdb: "106", naiyou: "落馬", tanshuku: "落馬" },
    { code: 107, jrdb: "107", naiyou: "輸送ダメ", tanshuku: "輸送ダメ" },
    { code: 108, jrdb: "108", naiyou: "馬込ダメ", tanshuku: "馬込ダメ" },
    { code: 109, jrdb: "109", naiyou: "冬ダメ", tanshuku: "冬ダメ" },
    { code: 110, jrdb: "110", naiyou: "外逃解消", tanshuku: "外逃解消" },
    { code: 111, jrdb: "111", naiyou: "鞍ズレ", tanshuku: "鞍ズレ" },
    { code: 112, jrdb: "112", naiyou: "ジリ脚", tanshuku: "ジリ脚" },
    { code: 113, jrdb: "113", naiyou: "口向解消", tanshuku: "口向解消" },
    { code: 114, jrdb: "114", naiyou: "ローカル向", tanshuku: "ロカ向き" },
    { code: 115, jrdb: "115", naiyou: "外逃げる", tanshuku: "外逃げる" },
    { code: 116, jrdb: "116", naiyou: "恐い解消", tanshuku: "恐い解消" },
    { code: 117, jrdb: "117", naiyou: "ソエ解消", tanshuku: "ソエ解消" },
    { code: 118, jrdb: "118", naiyou: "モタレ解消", tanshuku: "モタレ消" },
    { code: 119, jrdb: "119", naiyou: "コーナーワーク×", tanshuku: "コーナ×" },
    { code: 120, jrdb: "120", naiyou: "小回り向き", tanshuku: "小回向き" },
    { code: 121, jrdb: "121", naiyou: "外枠発走", tanshuku: "外枠発走" },
    { code: 122, jrdb: "122", naiyou: "冬○", tanshuku: "冬○" },
    { code: 123, jrdb: "123", naiyou: "追って甘い", tanshuku: "追甘い" },
    { code: 124, jrdb: "124", naiyou: "坂○", tanshuku: "坂○" },
    { code: 125, jrdb: "125", naiyou: "体質弱い", tanshuku: "体質弱い" },
    { code: 126, jrdb: "126", naiyou: "走る気ない", tanshuku: "走る気×" },
    { code: 127, jrdb: "127", naiyou: "素質あり", tanshuku: "素質あり" },
    { code: 128, jrdb: "128", naiyou: "鉄砲○", tanshuku: "鉄砲○" },
    { code: 129, jrdb: "129", naiyou: "気が小さい", tanshuku: "気小さい" },
    { code: 130, jrdb: "130", naiyou: "終い甘い", tanshuku: "終い甘い" },
    { code: 131, jrdb: "131", naiyou: "他馬気にする", tanshuku: "他馬気に" },
    { code: 132, jrdb: "132", naiyou: "輸送熱", tanshuku: "輸送熱" },
    { code: 133, jrdb: "133", naiyou: "パドック転倒", tanshuku: "パド転倒" },
    { code: 134, jrdb: "134", naiyou: "ゲート内転倒", tanshuku: "ゲト転倒" },
    { code: 135, jrdb: "135", naiyou: "ハミ外す", tanshuku: "ハミ外す" },
    { code: 136, jrdb: "136", naiyou: "腰悪い", tanshuku: "腰悪い" },
    { code: 137, jrdb: "137", naiyou: "ソエ焼き", tanshuku: "ソエ焼き" },
    { code: 138, jrdb: "138", naiyou: "筋肉痛", tanshuku: "筋肉痛" },
    { code: 140, jrdb: "140", naiyou: "ゲート良い", tanshuku: "ゲート○" },
    { code: 141, jrdb: "141", naiyou: "ゲート悪い", tanshuku: "ゲート×" },
    { code: 142, jrdb: "142", naiyou: "気が強い", tanshuku: "気が強い" },
    { code: 143, jrdb: "143", naiyou: "斤量泣き", tanshuku: "斤量泣き" },
    { code: 144, jrdb: "144", naiyou: "器用さ欠く", tanshuku: "器用さ欠" },
    { code: 145, jrdb: "145", naiyou: "使い込む×", tanshuku: "使込×" },
    { code: 146, jrdb: "146", naiyou: "手前替え×", tanshuku: "手前替×" },
    { code: 147, jrdb: "147", naiyou: "小回り×", tanshuku: "小回り×" },
    { code: 148, jrdb: "148", naiyou: "追って甘い", tanshuku: "追って甘" },
    { code: 149, jrdb: "149", naiyou: "後方から", tanshuku: "後方から" },
    { code: 150, jrdb: "150", naiyou: "お終い確実", tanshuku: "終い確実" },
    { code: 151, jrdb: "151", naiyou: "展開待ち", tanshuku: "展開待ち" },
    { code: 152, jrdb: "152", naiyou: "砂被る○", tanshuku: "砂被る○" },
    { code: 153, jrdb: "153", naiyou: "砂被る×", tanshuku: "砂被る×" },
    { code: 154, jrdb: "154", naiyou: "コーナーワーク○", tanshuku: "コーナ○" },
    { code: 155, jrdb: "155", naiyou: "坂×", tanshuku: "坂×" },
    { code: 156, jrdb: "156", naiyou: "ふらつく", tanshuku: "ふらつく" },
    { code: 157, jrdb: "157", naiyou: "ダッシュ○", tanshuku: "ダッシ○" },
    { code: 158, jrdb: "158", naiyou: "ダッシュ×", tanshuku: "ダッシ×" },
    { code: 159, jrdb: "159", naiyou: "フワフワ", tanshuku: "フワフワ" },
    { code: 160, jrdb: "160", naiyou: "中山向き", tanshuku: "中山向き" },
    { code: 161, jrdb: "161", naiyou: "府中向き", tanshuku: "府中向き" },
    { code: 162, jrdb: "162", naiyou: "腰甘い", tanshuku: "腰甘い" },
    { code: 163, jrdb: "163", naiyou: "怯む", tanshuku: "怯む" },
    { code: 164, jrdb: "164", naiyou: "足元弱い", tanshuku: "足元弱い" },
    { code: 165, jrdb: "165", naiyou: "馬気", tanshuku: "馬気" },
    { code: 166, jrdb: "166", naiyou: "歩様悪い", tanshuku: "歩様悪い" },
    { code: 167, jrdb: "167", naiyou: "気難しい", tanshuku: "気難しい" },
    { code: 168, jrdb: "168", naiyou: "小頭数○", tanshuku: "小頭数○" },
    { code: 169, jrdb: "169", naiyou: "ノメル", tanshuku: "ノメル" },
    { code: 170, jrdb: "170", naiyou: "トウ骨", tanshuku: "トウ骨" },
    { code: 171, jrdb: "171", naiyou: "追って頭上げる", tanshuku: "追頭上る" },
    { code: 172, jrdb: "172", naiyou: "砂被頭上げる", tanshuku: "砂被頭上" },
    { code: 173, jrdb: "173", naiyou: "広いコース向き", tanshuku: "広馬場向" },
    { code: 174, jrdb: "174", naiyou: "ラチ接触", tanshuku: "ラチ接触" },
    { code: 175, jrdb: "175", naiyou: "エビ", tanshuku: "エビ" },
    { code: 176, jrdb: "176", naiyou: "フケ", tanshuku: "フケ" },
    { code: 177, jrdb: "177", naiyou: "追ってしっかり", tanshuku: "追って○" },
    { code: 178, jrdb: "178", naiyou: "トモ落とす", tanshuku: "トモ落す" },
    { code: 179, jrdb: "179", naiyou: "外被せられる×", tanshuku: "外被る×" },
    { code: 180, jrdb: "180", naiyou: "泥被る○", tanshuku: "泥被る○" },
    { code: 181, jrdb: "181", naiyou: "泥被る×", tanshuku: "泥被る×" },
    { code: 182, jrdb: "182", naiyou: "一頭だと気を抜く", tanshuku: "一頭気抜" },
    { code: 183, jrdb: "183", naiyou: "ラチ頼る", tanshuku: "ラチ頼る" },
    { code: 184, jrdb: "184", naiyou: "耳絞る", tanshuku: "耳絞る" },
    { code: 185, jrdb: "185", naiyou: "首使い○", tanshuku: "首使い○" },
    { code: 186, jrdb: "186", naiyou: "首使い×", tanshuku: "首使い×" },
    { code: 187, jrdb: "187", naiyou: "砂被○", tanshuku: "砂被○" },
    { code: 188, jrdb: "188", naiyou: "砂被×", tanshuku: "砂被×" },
    { code: 189, jrdb: "189", naiyou: "フットワーク×", tanshuku: "フット×" },
    { code: 190, jrdb: "190", naiyou: "中間角膜炎", tanshuku: "中間角膜" },
    { code: 191, jrdb: "191", naiyou: "中間挫跖", tanshuku: "中間挫跖" },
    { code: 192, jrdb: "192", naiyou: "気性成長", tanshuku: "気性成長" },
    { code: 193, jrdb: "193", naiyou: "拍車", tanshuku: "拍車" },
    { code: 194, jrdb: "194", naiyou: "気性若い", tanshuku: "気性若い" },
    { code: 195, jrdb: "195", naiyou: "フレグモーネ", tanshuku: "フレグモ" },
    { code: 196, jrdb: "196", naiyou: "入線後故障", tanshuku: "入線故障" },
    { code: 197, jrdb: "197", naiyou: "道中気を抜く", tanshuku: "道中気抜" },
    { code: 198, jrdb: "198", naiyou: "直線長いコース向き", tanshuku: "直長向き" },
    { code: 199, jrdb: "199", naiyou: "外から被せられる×", tanshuku: "外被る×" },
    { code: 200, jrdb: "200", naiyou: "トモの状態悪い", tanshuku: "トモ悪い" },
    { code: 201, jrdb: "201", naiyou: "飛越○", tanshuku: "飛越○" },
    { code: 202, jrdb: "202", naiyou: "飛越×", tanshuku: "飛越×" },
    { code: 203, jrdb: "203", naiyou: "水濠○", tanshuku: "水濠○" },
    { code: 204, jrdb: "204", naiyou: "水濠×", tanshuku: "水濠×" },
    { code: 205, jrdb: "205", naiyou: "飛越に気を遣う", tanshuku: "飛越気遣" },
    { code: 206, jrdb: "206", naiyou: "落馬影響", tanshuku: "落馬影響" },
    { code: 207, jrdb: "207", naiyou: "着地○", tanshuku: "着地○" },
    { code: 208, jrdb: "208", naiyou: "着地×", tanshuku: "着地×" },
    { code: 209, jrdb: "209", naiyou: "立ち回り○", tanshuku: "立回り○" },
    { code: 210, jrdb: "210", naiyou: "立ち回り×", tanshuku: "立回り×" },
    { code: 211, jrdb: "211", naiyou: "飛越慎重", tanshuku: "飛越慎重" },
    { code: 212, jrdb: "212", naiyou: "平地力○", tanshuku: "平地力○" },
    { code: 213, jrdb: "213", naiyou: "平地力×", tanshuku: "平地力×" },
    { code: 215, jrdb: "215", naiyou: "スタミナ○", tanshuku: "スタミ○" },
    { code: 216, jrdb: "216", naiyou: "スタミナ×", tanshuku: "スタミ×" },
    { code: 217, jrdb: "217", naiyou: "道悪○", tanshuku: "道悪○" },
    { code: 218, jrdb: "218", naiyou: "道悪×", tanshuku: "道悪×" },
    { code: 219, jrdb: "219", naiyou: "飛越時気を抜く", tanshuku: "飛越気抜" },
    { code: 221, jrdb: "221", naiyou: "障害接触", tanshuku: "障害接触" },
    { code: 222, jrdb: "222", naiyou: "バンケット×", tanshuku: "バンケ×" },
    { code: 223, jrdb: "223", naiyou: "斜飛", tanshuku: "斜飛" },
    { code: 224, jrdb: "224", naiyou: "バンケット○", tanshuku: "バンケ○" },
    { code: 225, jrdb: "225", naiyou: "飛越高い", tanshuku: "飛越高い" },
    { code: 226, jrdb: "226", naiyou: "飛越△", tanshuku: "飛越△" },
    { code: 227, jrdb: "227", naiyou: "飛越安定", tanshuku: "飛越安定" },
    { code: 228, jrdb: "228", naiyou: "着地△", tanshuku: "着地△" },
    { code: 229, jrdb: "229", naiyou: "水濠トモ落", tanshuku: "水トモ落" },
    { code: 230, jrdb: "230", naiyou: "障害飛ばず", tanshuku: "障飛ばず" },
    { code: 231, jrdb: "231", naiyou: "障害調教再審査", tanshuku: "障調再審" },
    { code: 232, jrdb: "232", naiyou: "終ダ×", tanshuku: "終ダ×" },
    { code: 233, jrdb: "233", naiyou: "落馬寸前", tanshuku: "落馬寸前" },
    { code: 234, jrdb: "234", naiyou: "時計掛○", tanshuku: "時計掛○" },
    { code: 235, jrdb: "235", naiyou: "時計掛×", tanshuku: "時計掛×" },
    { code: 236, jrdb: "236", naiyou: "飛越◎", tanshuku: "飛越◎" },
    { code: 237, jrdb: "237", naiyou: "斤量応", tanshuku: "斤量応" },
    { code: 238, jrdb: "238", naiyou: "平地力◎", tanshuku: "平地力◎" },
    { code: 239, jrdb: "239", naiyou: "障害調教注意", tanshuku: "障調注意" },
    { code: 240, jrdb: "240", naiyou: "終いダ○", tanshuku: "終いダ○" },
    { code: 241, jrdb: "241", naiyou: "落馬後遺症残", tanshuku: "落後遺残" },
    { code: 242, jrdb: "242", naiyou: "飛越時ブレーキ", tanshuku: "飛越ブレ" },
    { code: 245, jrdb: "245", naiyou: "直線芝○", tanshuku: "直線芝○" },
    { code: 246, jrdb: "246", naiyou: "直線芝×", tanshuku: "直線芝×" },
    { code: 247, jrdb: "247", naiyou: "落馬再騎乗", tanshuku: "落馬再乗" },
    { code: 249, jrdb: "249", naiyou: "背が低い", tanshuku: "背が低い" },
    { code: 250, jrdb: "250", naiyou: "脚短い", tanshuku: "脚短い" },
    { code: 251, jrdb: "251", naiyou: "連続障害○", tanshuku: "連障害○" },
    { code: 252, jrdb: "252", naiyou: "連続障害×", tanshuku: "連障害×" },
    { code: 253, jrdb: "253", naiyou: "踏み切り○", tanshuku: "踏切○" },
    { code: 254, jrdb: "254", naiyou: "踏み切り×", tanshuku: "踏切×" },
    { code: 255, jrdb: "255", naiyou: "助走○", tanshuku: "助走○" },
    { code: 256, jrdb: "256", naiyou: "助走×", tanshuku: "助走×" },
    { code: 257, jrdb: "257", naiyou: "右斜飛", tanshuku: "右斜飛" },
    { code: 258, jrdb: "258", naiyou: "左斜飛", tanshuku: "左斜飛" },
    { code: 301, jrdb: "301", naiyou: "非力", tanshuku: "非力" },
    { code: 302, jrdb: "302", naiyou: "腰良化", tanshuku: "腰良化" },
    { code: 303, jrdb: "303", naiyou: "トモ良化", tanshuku: "トモ良化" },
    { code: 304, jrdb: "304", naiyou: "高脚使う", tanshuku: "高脚使う" },
    { code: 305, jrdb: "305", naiyou: "平坦向き", tanshuku: "平坦向き" },
    { code: 306, jrdb: "306", naiyou: "遊びながら走る", tanshuku: "遊び走る" },
    { code: 307, jrdb: "307", naiyou: "尻尾振る", tanshuku: "尻尾振る" },
    { code: 308, jrdb: "308", naiyou: "揉まれ弱い解消", tanshuku: "揉弱解消" },
    { code: 309, jrdb: "309", naiyou: "他馬と接触", tanshuku: "他馬接触" },
    { code: 310, jrdb: "310", naiyou: "レース中脚気にする", tanshuku: "R中脚気" },
    { code: 311, jrdb: "311", naiyou: "揉まれ強い", tanshuku: "揉れ強い" },
    { code: 313, jrdb: "313", naiyou: "トモ治療中", tanshuku: "ト治療中" },
    { code: 314, jrdb: "314", naiyou: "熱発明け", tanshuku: "熱発明け" },
    { code: 315, jrdb: "315", naiyou: "一頭だと走る気出す", tanshuku: "一頭走好" },
    { code: 316, jrdb: "316", naiyou: "口で息をする", tanshuku: "口で息" },
    { code: 317, jrdb: "317", naiyou: "口が硬い", tanshuku: "口が硬い" },
    { code: 320, jrdb: "320", naiyou: "スピード非凡", tanshuku: "スピ非凡" },
    { code: 321, jrdb: "321", naiyou: "脚を外に振って走る", tanshuku: "脚外振走" },
    { code: 322, jrdb: "322", naiyou: "喉弱い", tanshuku: "喉弱い" },
    { code: 323, jrdb: "323", naiyou: "背中が良い", tanshuku: "背中良い" },
    { code: 324, jrdb: "324", naiyou: "レース中故障(入線)", tanshuku: "R中故障" },
    { code: 325, jrdb: "325", naiyou: "器用", tanshuku: "器用" },
    { code: 326, jrdb: "326", naiyou: "次走ハミ替え○", tanshuku: "次ハミ○" },
    { code: 327, jrdb: "327", naiyou: "今回ハミ替え○", tanshuku: "今ハミ○" },
    { code: 328, jrdb: "328", naiyou: "今回ハミ替え×", tanshuku: "今ハミ×" },
    { code: 329, jrdb: "329", naiyou: "連闘○", tanshuku: "連闘○" },
    { code: 330, jrdb: "330", naiyou: "輸送弱い", tanshuku: "輸送弱い" },
    { code: 331, jrdb: "331", naiyou: "脚元悪い", tanshuku: "脚元悪い" },
    { code: 332, jrdb: "332", naiyou: "使い込む○", tanshuku: "使込○" },
    { code: 333, jrdb: "333", naiyou: "鉄砲×", tanshuku: "鉄砲×" },
    { code: 334, jrdb: "334", naiyou: "中間順調さ欠く", tanshuku: "中順調欠" },
    { code: 335, jrdb: "335", naiyou: "中間放馬", tanshuku: "中間放馬" },
    { code: 336, jrdb: "336", naiyou: "ゲートもたれ", tanshuku: "ゲもたれ" },
    { code: 337, jrdb: "337", naiyou: "ベタ爪", tanshuku: "ベタ爪" },
    { code: 338, jrdb: "338", naiyou: "最内枠×", tanshuku: "最内枠×" },
    { code: 339, jrdb: "339", naiyou: "パドック落馬", tanshuku: "パド落馬" },
    { code: 340, jrdb: "340", naiyou: "夏○", tanshuku: "夏○" },
    { code: 341, jrdb: "341", naiyou: "夏×", tanshuku: "夏×" },
    { code: 342, jrdb: "342", naiyou: "歩様良化", tanshuku: "歩様良化" },
    { code: 343, jrdb: "343", naiyou: "(競争中)鼻出血", tanshuku: "R中鼻血" },
    { code: 344, jrdb: "344", naiyou: "滞在競馬○", tanshuku: "滞競馬○" },
    { code: 345, jrdb: "345", naiyou: "リズム悪い", tanshuku: "リズム悪" },
    { code: 346, jrdb: "346", naiyou: "皮膚病", tanshuku: "皮膚病" },
    { code: 347, jrdb: "347", naiyou: "(馬場入場後)暴走", tanshuku: "馬入暴走" },
    { code: 348, jrdb: "348", naiyou: "外傷", tanshuku: "外傷" },
    { code: 349, jrdb: "349", naiyou: "タイムオーバー", tanshuku: "Ｔオーバ" },
    { code: 350, jrdb: "350", naiyou: "レース中骨折", tanshuku: "R中骨折" },
    { code: 351, jrdb: "351", naiyou: "舌がハミ越す", tanshuku: "舌ハミ越" },
    { code: 352, jrdb: "352", naiyou: "ハミ頼る", tanshuku: "ハミ頼る" },
    { code: 353, jrdb: "353", naiyou: "レース前落鉄", tanshuku: "R前落鉄" },
    { code: 354, jrdb: "354", naiyou: "ハミもたれ", tanshuku: "ハミもた" },
    { code: 355, jrdb: "355", naiyou: "トモ疲れ", tanshuku: "トモ疲れ" },
    { code: 356, jrdb: "356", naiyou: "冬毛出てくる", tanshuku: "冬毛咲く" },
    { code: 357, jrdb: "357", naiyou: "声で気合", tanshuku: "声で気合" },
    { code: 358, jrdb: "358", naiyou: "疲れ気味", tanshuku: "疲れ気味" },
    { code: 359, jrdb: "359", naiyou: "砂被ハミ掛悪い", tanshuku: "砂ハミ悪" },
    { code: 360, jrdb: "360", naiyou: "ブリ効果あり", tanshuku: "ブ効果○" },
    { code: 361, jrdb: "361", naiyou: "脚不安解消", tanshuku: "脚不安消" },
    { code: 362, jrdb: "362", naiyou: "水浮ダ×", tanshuku: "水浮ダ×" },
    { code: 363, jrdb: "363", naiyou: "躓きやすい", tanshuku: "躓きやす" },
    { code: 364, jrdb: "364", naiyou: "札幌向き", tanshuku: "札幌向き" },
    { code: 365, jrdb: "365", naiyou: "函館向き", tanshuku: "函館向き" },
    { code: 366, jrdb: "366", naiyou: "福島向き", tanshuku: "福島向き" },
    { code: 367, jrdb: "367", naiyou: "新潟向き", tanshuku: "新潟向き" },
    { code: 368, jrdb: "368", naiyou: "中京向き", tanshuku: "中京向き" },
    { code: 369, jrdb: "369", naiyou: "阪神向き", tanshuku: "阪神向き" },
    { code: 370, jrdb: "370", naiyou: "京都向き", tanshuku: "京都向き" },
    { code: 371, jrdb: "371", naiyou: "小倉向き", tanshuku: "小倉向き" },
    { code: 372, jrdb: "372", naiyou: "鳴く", tanshuku: "鳴く" },
    { code: 373, jrdb: "373", naiyou: "夏負け気味", tanshuku: "夏負気味" },
    { code: 374, jrdb: "374", naiyou: "タマ", tanshuku: "タマ" },
    { code: 375, jrdb: "375", naiyou: "ツメ悪い", tanshuku: "ツメ悪い" },
    { code: 376, jrdb: "376", naiyou: "多頭数×", tanshuku: "多頭数×" },
    { code: 378, jrdb: "378", naiyou: "シャド効果あり", tanshuku: "鼻効果○" },
    { code: 379, jrdb: "379", naiyou: "馬場入場後転倒", tanshuku: "馬入転倒" },
    { code: 380, jrdb: "380", naiyou: "膠着", tanshuku: "膠着" },
    { code: 381, jrdb: "381", naiyou: "体質シッカリ", tanshuku: "体質強し" },
    { code: 382, jrdb: "382", naiyou: "喉良化", tanshuku: "喉良化" },
    { code: 383, jrdb: "383", naiyou: "芝切れ目が飛ぶ", tanshuku: "芝生飛ぶ" },
    { code: 384, jrdb: "384", naiyou: "渋馬場○", tanshuku: "渋馬場○" },
    { code: 385, jrdb: "385", naiyou: "渋馬場×", tanshuku: "渋馬場×" },
    { code: 386, jrdb: "386", naiyou: "メンコ効果あり", tanshuku: "面子効果" },
    { code: 387, jrdb: "387", naiyou: "不利", tanshuku: "不利" },
    { code: 388, jrdb: "388", naiyou: "アオル", tanshuku: "アオル" },
    { code: 389, jrdb: "389", naiyou: "ブリ外効果あり", tanshuku: "ブ外効○" },
    { code: 390, jrdb: "390", naiyou: "京都×", tanshuku: "京都×" },
    { code: 391, jrdb: "391", naiyou: "距離長", tanshuku: "距離長" },
    { code: 392, jrdb: "392", naiyou: "距離短", tanshuku: "距離短" },
    { code: 393, jrdb: "393", naiyou: "鉄唇横", tanshuku: "鉄唇横" },
    { code: 394, jrdb: "394", naiyou: "瞬発力非凡", tanshuku: "瞬発非凡" },
    { code: 395, jrdb: "395", naiyou: "スピード有", tanshuku: "スピ有り" },
    { code: 396, jrdb: "396", naiyou: "スピード無", tanshuku: "スピ無し" },
    { code: 397, jrdb: "397", naiyou: "集中力出る", tanshuku: "集中力○" },
    { code: 398, jrdb: "398", naiyou: "集中力ない", tanshuku: "集中力×" },
    { code: 399, jrdb: "399", naiyou: "下を気にする", tanshuku: "下気する" },
    { code: 400, jrdb: "400", naiyou: "内側に斜行", tanshuku: "内側斜行" },
    { code: 401, jrdb: "401", naiyou: "外側に斜行", tanshuku: "外側斜行" },
    { code: 402, jrdb: "402", naiyou: "返し馬入念", tanshuku: "返馬入念" },
    { code: 403, jrdb: "403", naiyou: "(道中)息入る", tanshuku: "R息入る" },
    { code: 404, jrdb: "404", naiyou: "(道中)息入らず", tanshuku: "R息入ず" },
    { code: 405, jrdb: "405", naiyou: "ハミ替え2走目", tanshuku: "ハ替2走" },
    { code: 406, jrdb: "406", naiyou: "ハミ替え3走目", tanshuku: "ハ替3走" },
    { code: 407, jrdb: "407", naiyou: "今回馬具替え○", tanshuku: "今具替○" },
    { code: 408, jrdb: "408", naiyou: "今回馬具替え×", tanshuku: "今具替×" },
    { code: 409, jrdb: "409", naiyou: "直線手前替える", tanshuku: "直手前替" },
    { code: 410, jrdb: "410", naiyou: "本格化", tanshuku: "本格化" },
    { code: 411, jrdb: "411", naiyou: "ハミ取る", tanshuku: "ハミ取る" },
    { code: 412, jrdb: "412", naiyou: "ハミ取らず", tanshuku: "ハミ取ず" },
    { code: 413, jrdb: "413", naiyou: "躓く", tanshuku: "躓く" },
    { code: 414, jrdb: "414", naiyou: "輸送慣れ", tanshuku: "輸送慣れ" },
    { code: 415, jrdb: "415", naiyou: "大外回る", tanshuku: "大外回る" },
    { code: 416, jrdb: "416", naiyou: "コズミ解消", tanshuku: "コズミ消" },
    { code: 417, jrdb: "417", naiyou: "攻め軽目", tanshuku: "攻め軽目" },
    { code: 418, jrdb: "418", naiyou: "急仕上げ", tanshuku: "急仕上げ" },
    { code: 419, jrdb: "419", naiyou: "掛かる", tanshuku: "掛かる" },
    { code: 420, jrdb: "420", naiyou: "掛かり気味", tanshuku: "掛り気味" },
    { code: 421, jrdb: "421", naiyou: "突っ張る", tanshuku: "突っ張る" },
    { code: 422, jrdb: "422", naiyou: "行きたがる", tanshuku: "行たがる" },
    { code: 423, jrdb: "423", naiyou: "デキ一息", tanshuku: "デキ一息" },
    { code: 424, jrdb: "424", naiyou: "出走停止", tanshuku: "出走停止" },
    { code: 425, jrdb: "425", naiyou: "調教再審査", tanshuku: "調教再審" },
    { code: 426, jrdb: "426", naiyou: "発走再審査", tanshuku: "発走再審" },
    { code: 427, jrdb: "427", naiyou: "発走調教再審査", tanshuku: "発調再審" },
    { code: 428, jrdb: "428", naiyou: "枠内駐立不良", tanshuku: "枠駐不良" },
    { code: 429, jrdb: "429", naiyou: "枠入不良", tanshuku: "枠入不良" },
    { code: 430, jrdb: "430", naiyou: "阪神×", tanshuku: "阪神×" },
    { code: 431, jrdb: "431", naiyou: "腰力つく", tanshuku: "腰力つく" },
    { code: 432, jrdb: "432", naiyou: "連闘×", tanshuku: "連闘×" },
    { code: 433, jrdb: "433", naiyou: "パワー○", tanshuku: "パワー○" },
    { code: 434, jrdb: "434", naiyou: "スタート芝×", tanshuku: "スタ芝×" },
    { code: 435, jrdb: "435", naiyou: "息切れ", tanshuku: "息切れ" },
    { code: 436, jrdb: "436", naiyou: "逆手前", tanshuku: "逆手前" },
    { code: 437, jrdb: "437", naiyou: "気を抜く", tanshuku: "気を抜く" },
    { code: 438, jrdb: "438", naiyou: "二走ボケ", tanshuku: "二走ボケ" },
    { code: 439, jrdb: "439", naiyou: "捌き硬い", tanshuku: "捌き硬い" },
    { code: 440, jrdb: "440", naiyou: "追い通し", tanshuku: "追い通し" },
    { code: 441, jrdb: "441", naiyou: "余力なし", tanshuku: "余力なし" },
    { code: 442, jrdb: "442", naiyou: "いい脚長く使う", tanshuku: "良脚長使" },
    { code: 443, jrdb: "443", naiyou: "落ち着きほしい", tanshuku: "落着ほし" },
    { code: 444, jrdb: "444", naiyou: "落ち着きでる", tanshuku: "落着でる" },
    { code: 445, jrdb: "445", naiyou: "レースせず", tanshuku: "Rせず" },
    { code: 446, jrdb: "446", naiyou: "シャド外効果アリ", tanshuku: "鼻外効○" },
    { code: 447, jrdb: "447", naiyou: "トモぶつける", tanshuku: "トモぶつ" },
    { code: 448, jrdb: "448", naiyou: "バランス崩す", tanshuku: "バラ崩す" },
    { code: 449, jrdb: "449", naiyou: "ペース速い○", tanshuku: "P速い○" },
    { code: 450, jrdb: "450", naiyou: "ペース速い×", tanshuku: "P速い×" },
    { code: 451, jrdb: "451", naiyou: "ペース遅い○", tanshuku: "P遅い○" },
    { code: 452, jrdb: "452", naiyou: "ペース遅い×", tanshuku: "P遅い×" },
    { code: 453, jrdb: "453", naiyou: "モタつく", tanshuku: "モタつく" },
    { code: 454, jrdb: "454", naiyou: "調教注意", tanshuku: "調教注意" },
    { code: 455, jrdb: "455", naiyou: "返し馬ウルサイ", tanshuku: "返馬煩い" },
    { code: 456, jrdb: "456", naiyou: "返し馬できない", tanshuku: "返できな" },
    { code: 457, jrdb: "457", naiyou: "馬具変更2走目", tanshuku: "具変2走" },
    { code: 458, jrdb: "458", naiyou: "中間フレグモーネ", tanshuku: "中間フレ" },
    { code: 459, jrdb: "459", naiyou: "口割る", tanshuku: "口割る" },
    { code: 460, jrdb: "460", naiyou: "ズブイ解消", tanshuku: "ズブイ消" },
    { code: 461, jrdb: "461", naiyou: "減量効果あり", tanshuku: "減量効○" },
    { code: 462, jrdb: "462", naiyou: "いい脚少しだけ", tanshuku: "良脚少し" },
    { code: 463, jrdb: "463", naiyou: "ダ少し速○", tanshuku: "ダ少速○" },
    { code: 464, jrdb: "464", naiyou: "ダ少し速×", tanshuku: "ダ少速×" },
    { code: 465, jrdb: "465", naiyou: "馬込平気", tanshuku: "馬込平気" },
    { code: 466, jrdb: "466", naiyou: "ないら", tanshuku: "ないら" },
    { code: 467, jrdb: "467", naiyou: "蹄良化", tanshuku: "蹄良化" },
    { code: 468, jrdb: "468", naiyou: "フラッシュ×", tanshuku: "フラッ×" },
    { code: 469, jrdb: "469", naiyou: "ひざ外傷", tanshuku: "ひざ外傷" },
    { code: 470, jrdb: "470", naiyou: "スネ外傷", tanshuku: "スネ外傷" },
    { code: 471, jrdb: "471", naiyou: "食い細", tanshuku: "食い細" },
    { code: 472, jrdb: "472", naiyou: "瞬発力△", tanshuku: "瞬発力△" },
    { code: 473, jrdb: "473", naiyou: "エンジン掛速", tanshuku: "加速速い" },
    { code: 474, jrdb: "474", naiyou: "エンジン掛遅", tanshuku: "加速遅い" },
    { code: 475, jrdb: "475", naiyou: "裂蹄のため次走延期", tanshuku: "裂蹄次延" },
    { code: 476, jrdb: "476", naiyou: "ゲート音怖がる", tanshuku: "ゲ音怖い" },
    { code: 477, jrdb: "477", naiyou: "軟ら芝×", tanshuku: "軟ら芝×" },
    { code: 478, jrdb: "478", naiyou: "次走良化気配", tanshuku: "次良気配" },
    { code: 479, jrdb: "479", naiyou: "次走一変可", tanshuku: "次一変可" },
    { code: 480, jrdb: "480", naiyou: "芝大丈夫", tanshuku: "芝大丈夫" },
    { code: 481, jrdb: "481", naiyou: "ダ大丈夫", tanshuku: "ダ大丈夫" },
    { code: 482, jrdb: "482", naiyou: "ゲート潜る", tanshuku: "ゲ潜る" },
    { code: 483, jrdb: "483", naiyou: "連闘ダメ", tanshuku: "連闘ダメ" },
    { code: 484, jrdb: "484", naiyou: "前行くとダメ", tanshuku: "前行く×" },
    { code: 485, jrdb: "485", naiyou: "見せ場なし", tanshuku: "見せ場×" },
    { code: 486, jrdb: "486", naiyou: "後方まま", tanshuku: "後方まま" },
    { code: 487, jrdb: "487", naiyou: "中間熱発", tanshuku: "中間熱発" },
    { code: 488, jrdb: "488", naiyou: "軟ら芝○", tanshuku: "軟ら芝○" },
    { code: 489, jrdb: "489", naiyou: "故障アオリ食", tanshuku: "故障ア食" },
    { code: 490, jrdb: "490", naiyou: "馬込△", tanshuku: "馬込△" },
    { code: 491, jrdb: "491", naiyou: "フットワーク△", tanshuku: "脚捌き△" },
    { code: 492, jrdb: "492", naiyou: "トビ小さい", tanshuku: "トビ小さ" },
    { code: 493, jrdb: "493", naiyou: "挫跖のため次走延期", tanshuku: "挫跖次延" },
    { code: 494, jrdb: "494", naiyou: "熱発のため次走延期", tanshuku: "熱発次延" },
    { code: 495, jrdb: "495", naiyou: "裂蹄のため放牧", tanshuku: "裂蹄放牧" },
    { code: 496, jrdb: "496", naiyou: "輸送食い細", tanshuku: "輸送食細" },
    { code: 497, jrdb: "497", naiyou: "皮膚色抜ける", tanshuku: "皮色抜る" },
    { code: 498, jrdb: "498", naiyou: "馬体緩める", tanshuku: "馬体緩る" },
    { code: 499, jrdb: "499", naiyou: "ブリンカー2走目", tanshuku: "ブ2走目" },
    { code: 500, jrdb: "500", naiyou: "ブリンカー3走目", tanshuku: "ブ3走目" },
    { code: 501, jrdb: "501", naiyou: "感冒", tanshuku: "感冒" },
    { code: 502, jrdb: "502", naiyou: "疝痛", tanshuku: "疝痛" },
    { code: 503, jrdb: "503", naiyou: "角膜炎", tanshuku: "角膜炎" },
    { code: 504, jrdb: "504", naiyou: "右前踏創", tanshuku: "右前踏創" },
    { code: 505, jrdb: "505", naiyou: "左前踏創", tanshuku: "左前踏創" },
    { code: 506, jrdb: "506", naiyou: "右後踏創", tanshuku: "右後踏創" },
    { code: 507, jrdb: "507", naiyou: "左後踏創", tanshuku: "左後踏創" },
    { code: 508, jrdb: "508", naiyou: "両前踏創", tanshuku: "両前踏創" },
    { code: 509, jrdb: "509", naiyou: "両後踏創", tanshuku: "両後踏創" },
    { code: 510, jrdb: "510", naiyou: "右前管骨々膜炎", tanshuku: "右前骨膜" },
    { code: 511, jrdb: "511", naiyou: "左前管骨々膜炎", tanshuku: "左前骨膜" },
    { code: 512, jrdb: "512", naiyou: "右後管骨々膜炎", tanshuku: "右後骨膜" },
    { code: 513, jrdb: "513", naiyou: "左後管骨々膜炎", tanshuku: "左後骨膜" },
    { code: 514, jrdb: "514", naiyou: "両前管骨々膜炎", tanshuku: "両前骨膜" },
    { code: 515, jrdb: "515", naiyou: "両後管骨々膜炎", tanshuku: "両後骨膜" },
    { code: 516, jrdb: "516", naiyou: "右前肢挫創", tanshuku: "右前挫創" },
    { code: 517, jrdb: "517", naiyou: "左前肢挫創", tanshuku: "左前挫創" },
    { code: 518, jrdb: "518", naiyou: "右後肢挫創", tanshuku: "右後挫創" },
    { code: 519, jrdb: "519", naiyou: "左後肢挫創", tanshuku: "左後挫創" },
    { code: 520, jrdb: "520", naiyou: "両前肢挫創", tanshuku: "両前挫創" },
    { code: 521, jrdb: "521", naiyou: "両後肢挫創", tanshuku: "両後挫創" },
    { code: 522, jrdb: "522", naiyou: "右前球節炎", tanshuku: "右前球節" },
    { code: 523, jrdb: "523", naiyou: "左前球節炎", tanshuku: "左前球節" },
    { code: 524, jrdb: "524", naiyou: "右後球節炎", tanshuku: "右後球節" },
    { code: 525, jrdb: "525", naiyou: "左後球節炎", tanshuku: "左後球節" },
    { code: 526, jrdb: "526", naiyou: "両前球節炎", tanshuku: "両前球節" },
    { code: 527, jrdb: "527", naiyou: "両後球節炎", tanshuku: "両後球節" },
    { code: 528, jrdb: "528", naiyou: "右前球節部フレグモー", tanshuku: "右前フレ" },
    { code: 529, jrdb: "529", naiyou: "左前球節部フレグモー", tanshuku: "左前フレ" },
    { code: 530, jrdb: "530", naiyou: "右後球節部フレグモー", tanshuku: "右後フレ" },
    { code: 531, jrdb: "531", naiyou: "左後球節部フレグモー", tanshuku: "左後フレ" },
    { code: 532, jrdb: "532", naiyou: "両前球節部フレグモー", tanshuku: "両前フレ" },
    { code: 533, jrdb: "533", naiyou: "右前肢フレグモーネ", tanshuku: "右前フレ" },
    { code: 534, jrdb: "534", naiyou: "左前肢フレグモーネ", tanshuku: "左前フレ" },
    { code: 535, jrdb: "535", naiyou: "右後肢フレグモーネ", tanshuku: "右後フレ" },
    { code: 536, jrdb: "536", naiyou: "左後肢フレグモーネ", tanshuku: "左後フレ" },
    { code: 537, jrdb: "537", naiyou: "両前肢フレグモーネ", tanshuku: "両前フレ" },
    { code: 538, jrdb: "538", naiyou: "両後肢フレグモーネ", tanshuku: "両後フレ" },
    { code: 539, jrdb: "539", naiyou: "右前屈腱炎", tanshuku: "右前屈腱" },
    { code: 540, jrdb: "540", naiyou: "左前屈腱炎", tanshuku: "左前屈腱" },
    { code: 541, jrdb: "541", naiyou: "両前屈腱炎", tanshuku: "両前屈腱" },
    { code: 542, jrdb: "542", naiyou: "外傷性鼻出血", tanshuku: "外傷鼻血" },
    { code: 543, jrdb: "543", naiyou: "右前挫跖", tanshuku: "右前挫跖" },
    { code: 544, jrdb: "544", naiyou: "左前挫跖", tanshuku: "左前挫跖" },
    { code: 545, jrdb: "545", naiyou: "右後挫跖", tanshuku: "右後挫跖" },
    { code: 546, jrdb: "546", naiyou: "左後挫跖", tanshuku: "左後挫跖" },
    { code: 547, jrdb: "547", naiyou: "両後挫跖", tanshuku: "両後挫跖" },
    { code: 548, jrdb: "548", naiyou: "両前挫跖", tanshuku: "両前挫跖" },
    { code: 549, jrdb: "549", naiyou: "右前裂蹄", tanshuku: "右前裂蹄" },
    { code: 550, jrdb: "550", naiyou: "左前裂蹄", tanshuku: "左前裂蹄" },
    { code: 551, jrdb: "551", naiyou: "右後裂蹄", tanshuku: "右後裂蹄" },
    { code: 552, jrdb: "552", naiyou: "左後裂蹄", tanshuku: "左後裂蹄" },
    { code: 553, jrdb: "553", naiyou: "両前裂蹄", tanshuku: "両前裂蹄" },
    { code: 554, jrdb: "554", naiyou: "両後裂蹄", tanshuku: "両後裂蹄" },
    { code: 555, jrdb: "555", naiyou: "右寛跛行", tanshuku: "右寛跛行" },
    { code: 556, jrdb: "556", naiyou: "左寛跛行", tanshuku: "左寛跛行" },
    { code: 557, jrdb: "557", naiyou: "右肩跛行", tanshuku: "右肩跛行" },
    { code: 558, jrdb: "558", naiyou: "左肩跛行", tanshuku: "左肩跛行" },
    { code: 559, jrdb: "559", naiyou: "右前繋部挫創", tanshuku: "右前挫創" },
    { code: 560, jrdb: "560", naiyou: "左前繋部挫創", tanshuku: "左前挫創" },
    { code: 561, jrdb: "561", naiyou: "右後繋部挫創", tanshuku: "右後挫創" },
    { code: 562, jrdb: "562", naiyou: "左後繋部挫創", tanshuku: "左後挫創" },
    { code: 563, jrdb: "563", naiyou: "両前繋部挫創", tanshuku: "両前挫創" },
    { code: 564, jrdb: "564", naiyou: "両後繋部挫創", tanshuku: "両後挫創" },
    { code: 565, jrdb: "565", naiyou: "右第1骨々折", tanshuku: "右骨々折" },
    { code: 572, jrdb: "572", naiyou: "左第1指骨々折", tanshuku: "左指骨折" },
    { code: 573, jrdb: "573", naiyou: "ジンマシン", tanshuku: "蕁麻疹" },
    { code: 575, jrdb: "575", naiyou: "左前繋靭帯断裂", tanshuku: "左繋断裂" },
    { code: 576, jrdb: "576", naiyou: "左第1指関節脱臼", tanshuku: "左指脱臼" },
    { code: 578, jrdb: "578", naiyou: "左前屈腱部打撲傷", tanshuku: "左屈打撲" },
    { code: 579, jrdb: "579", naiyou: "右前屈腱断裂", tanshuku: "右屈断裂" },
    { code: 580, jrdb: "580", naiyou: "両前浅屈腱断裂", tanshuku: "両浅屈断" },
    { code: 581, jrdb: "581", naiyou: "寛骨々折", tanshuku: "寛骨々折" },
    { code: 582, jrdb: "582", naiyou: "右前浅屈腱不全断裂", tanshuku: "右屈不裂" },
    { code: 583, jrdb: "583", naiyou: "左前繋靭帯炎", tanshuku: "左繋帯炎" },
    { code: 584, jrdb: "584", naiyou: "右肘部フレグモーネ", tanshuku: "右肘フレ" },
    { code: 585, jrdb: "585", naiyou: "右前浅屈腱炎", tanshuku: "右浅屈腱" },
    { code: 586, jrdb: "586", naiyou: "左前腕部蹴傷", tanshuku: "左腕蹴傷" },
    { code: 587, jrdb: "587", naiyou: "右第1指関節脱臼", tanshuku: "右指脱臼" },
    { code: 588, jrdb: "588", naiyou: "キ甲部挫創", tanshuku: "キ甲挫創" },
    { code: 589, jrdb: "589", naiyou: "両腕接部挫創", tanshuku: "両腕挫創" },
    { code: 590, jrdb: "590", naiyou: "両頚部打撲傷", tanshuku: "頚部打撲" },
    { code: 591, jrdb: "591", naiyou: "疲労が著しいため除外", tanshuku: "疲労除外" },
    { code: 592, jrdb: "592", naiyou: "鞍傷", tanshuku: "鞍傷" },
    { code: 593, jrdb: "593", naiyou: "右第1指節種子骨々折", tanshuku: "右種骨折" },
    { code: 594, jrdb: "594", naiyou: "右腰角部挫創", tanshuku: "右腰挫創" },
    { code: 595, jrdb: "595", naiyou: "右前繋靭帯炎", tanshuku: "右繋靭炎" },
    { code: 596, jrdb: "596", naiyou: "両前腕部挫創", tanshuku: "両腕挫創" },
    { code: 597, jrdb: "597", naiyou: "右膝蓋部挫創", tanshuku: "右膝挫創" },
    { code: 598, jrdb: "598", naiyou: "左後蹄冠部挫創", tanshuku: "左蹄挫創" },
    { code: 599, jrdb: "599", naiyou: "左副手根骨々折", tanshuku: "左手骨折" },
    { code: 600, jrdb: "600", naiyou: "両飛節挫創", tanshuku: "両飛挫創" },
    { code: 601, jrdb: "601", naiyou: "寛跛行", tanshuku: "寛跛行" },
    { code: 602, jrdb: "602", naiyou: "便秘疝", tanshuku: "便秘疝" },
    { code: 603, jrdb: "603", naiyou: "右飛節炎", tanshuku: "右飛節炎" },
    { code: 604, jrdb: "604", naiyou: "右上眼瞼部挫創", tanshuku: "右眼挫創" },
    { code: 605, jrdb: "605", naiyou: "腰椎骨折", tanshuku: "腰椎骨折" },
    { code: 606, jrdb: "606", naiyou: "両前管部挫創", tanshuku: "両管挫創" },
    { code: 607, jrdb: "607", naiyou: "左腕節部挫創", tanshuku: "左腕挫創" },
    { code: 608, jrdb: "608", naiyou: "事故のため除外", tanshuku: "事故除外" },
    { code: 609, jrdb: "609", naiyou: "パドック蹄鉄打ち直し", tanshuku: "パ鉄打直" },
    { code: 610, jrdb: "610", naiyou: "左前球節部挫創", tanshuku: "左球挫創" },
    { code: 611, jrdb: "611", naiyou: "右大腿骨々折", tanshuku: "右腿骨折" },
    { code: 612, jrdb: "612", naiyou: "右前屈腱部打撲傷", tanshuku: "右打撲傷" },
    { code: 613, jrdb: "613", naiyou: "左第3中手骨複骨折", tanshuku: "左複骨折" },
    { code: 614, jrdb: "614", naiyou: "右口角節", tanshuku: "右口角節" },
    { code: 615, jrdb: "615", naiyou: "肩跛行", tanshuku: "肩跛行" },
    { code: 616, jrdb: "616", naiyou: "右前管部挫創", tanshuku: "右管挫創" },
    { code: 617, jrdb: "617", naiyou: "左第3指趾骨々折", tanshuku: "左指骨折" },
    { code: 618, jrdb: "618", naiyou: "左前繋靭帯炎", tanshuku: "左前繋炎" },
    { code: 619, jrdb: "619", naiyou: "右飛節部挫創", tanshuku: "右飛挫創" },
    { code: 620, jrdb: "620", naiyou: "左前蹄球炎", tanshuku: "左前蹄炎" },
    { code: 621, jrdb: "621", naiyou: "右下腿部挫創", tanshuku: "右腿挫創" },
    { code: 622, jrdb: "622", naiyou: "左第3指骨骨折", tanshuku: "左指骨折" },
    { code: 623, jrdb: "623", naiyou: "左腰角部挫創", tanshuku: "左腰挫創" },
    { code: 624, jrdb: "624", naiyou: "額部挫創", tanshuku: "額部挫創" },
    { code: 625, jrdb: "625", naiyou: "右第3中足骨々折", tanshuku: "右足骨折" },
    { code: 626, jrdb: "626", naiyou: "左飛節部挫創", tanshuku: "左飛挫創" },
    { code: 627, jrdb: "627", naiyou: "左後繋靭帯断裂", tanshuku: "左後繋裂" },
    { code: 628, jrdb: "628", naiyou: "左後管部打撲傷", tanshuku: "左管打撲" },
    { code: 629, jrdb: "629", naiyou: "右後管部挫創", tanshuku: "右管挫創" },
    { code: 630, jrdb: "630", naiyou: "左腰部打撲", tanshuku: "左腰打撲" },
    { code: 631, jrdb: "631", naiyou: "左前飛節炎", tanshuku: "左飛節炎" },
    { code: 632, jrdb: "632", naiyou: "頚部挫創", tanshuku: "頚部挫創" },
    { code: 633, jrdb: "633", naiyou: "左第3手根骨板状骨折", tanshuku: "左手骨折" },
    { code: 634, jrdb: "634", naiyou: "右前腕骨々折", tanshuku: "右腕骨折" },
    { code: 635, jrdb: "635", naiyou: "右前浅屈腱断裂", tanshuku: "右屈腱裂" },
    { code: 636, jrdb: "636", naiyou: "創傷性右角膜炎", tanshuku: "右角膜炎" },
    { code: 637, jrdb: "637", naiyou: "外傷性右鼻出血", tanshuku: "外鼻出血" },
    { code: 638, jrdb: "638", naiyou: "左上腕骨々折", tanshuku: "左腕骨折" },
    { code: 639, jrdb: "639", naiyou: "創傷性左角膜炎", tanshuku: "左角膜炎" },
    { code: 640, jrdb: "640", naiyou: "右腕節部挫創", tanshuku: "右腕挫創" },
    { code: 641, jrdb: "641", naiyou: "左前浅屈腱不全断裂", tanshuku: "左屈不裂" },
    { code: 642, jrdb: "642", naiyou: "右第3指骨々折", tanshuku: "右指骨折" },
    { code: 643, jrdb: "643", naiyou: "左前腕部挫創", tanshuku: "左腕挫創" },
    { code: 644, jrdb: "644", naiyou: "右前繋靭帯断裂", tanshuku: "右前繋裂" },
    { code: 645, jrdb: "645", naiyou: "蹄冠挫石", tanshuku: "蹄冠挫石" },
    { code: 646, jrdb: "646", naiyou: "右第1趾骨粉砕骨折", tanshuku: "右粉骨折" },
    { code: 647, jrdb: "647", naiyou: "左第3中手骨々折", tanshuku: "左手骨折" },
    { code: 648, jrdb: "648", naiyou: "左第3中足骨々折", tanshuku: "左足骨折" },
    { code: 649, jrdb: "649", naiyou: "左副手根骨複骨折", tanshuku: "左手骨折" },
    { code: 650, jrdb: "650", naiyou: "左橈骨遠位端骨折", tanshuku: "左遠骨折" },
    { code: 651, jrdb: "651", naiyou: "左前靭帯不全断裂", tanshuku: "左靭不裂" },
    { code: 652, jrdb: "652", naiyou: "急性心不全", tanshuku: "急心不全" },
    { code: 653, jrdb: "653", naiyou: "左肩部蹴傷", tanshuku: "左肩蹴傷" },
    { code: 654, jrdb: "654", naiyou: "左後球節部切創", tanshuku: "左後切創" },
    { code: 655, jrdb: "655", naiyou: "胸部フレグモーネ", tanshuku: "胸フレグ" },
    { code: 656, jrdb: "656", naiyou: "右第3中足骨複骨折", tanshuku: "右足骨折" },
    { code: 657, jrdb: "657", naiyou: "両前肢打撲傷", tanshuku: "両前肢傷" },
    { code: 658, jrdb: "658", naiyou: "右アキレス腱脱位", tanshuku: "右アキ脱" },
    { code: 659, jrdb: "659", naiyou: "左下腿骨複骨折", tanshuku: "左下骨折" },
    { code: 660, jrdb: "660", naiyou: "食道梗塞", tanshuku: "食道梗塞" },
    { code: 661, jrdb: "661", naiyou: "右前蹄球炎", tanshuku: "右前蹄炎" },
    { code: 662, jrdb: "662", naiyou: "左上腕骨々折", tanshuku: "左腕骨折" },
    { code: 663, jrdb: "663", naiyou: "左手根骨複骨折", tanshuku: "左手骨折" },
    { code: 664, jrdb: "664", naiyou: "左第1指骨粉砕骨折", tanshuku: "左粉骨折" },
    { code: 665, jrdb: "665", naiyou: "キ甲部打撲傷", tanshuku: "キ甲打撲" },
    { code: 666, jrdb: "666", naiyou: "左膝蓋部挫創", tanshuku: "左膝挫創" },
    { code: 667, jrdb: "667", naiyou: "右第3中足骨開放骨折", tanshuku: "右開骨折" },
    { code: 668, jrdb: "668", naiyou: "右肘腫", tanshuku: "右肘腫" },
    { code: 669, jrdb: "669", naiyou: "四肢挫創", tanshuku: "四肢挫創" },
    { code: 670, jrdb: "670", naiyou: "左第2指関節開放性脱", tanshuku: "左開脱臼" },
    { code: 671, jrdb: "671", naiyou: "左前繋靭帯不全断裂", tanshuku: "左靭不裂" },
    { code: 672, jrdb: "672", naiyou: "背部フレグモーネ", tanshuku: "背部フレ" },
    { code: 673, jrdb: "673", naiyou: "右前球節部挫創", tanshuku: "右前挫創" },
    { code: 674, jrdb: "674", naiyou: "左前浅屈腱断裂", tanshuku: "左浅断裂" },
    { code: 675, jrdb: "675", naiyou: "両後球節部挫創", tanshuku: "両後挫創" },
    { code: 676, jrdb: "676", naiyou: "右上腕骨々折", tanshuku: "右腕骨折" },
    { code: 677, jrdb: "677", naiyou: "右中手骨開放骨折", tanshuku: "右開骨折" },
    { code: 678, jrdb: "678", naiyou: "右脛骨々膜炎", tanshuku: "右脛骨炎" },
    { code: 679, jrdb: "679", naiyou: "左股関節脱臼", tanshuku: "左股脱臼" },
    { code: 680, jrdb: "680", naiyou: "左第3中足骨開放骨折", tanshuku: "左開骨折" },
    { code: 681, jrdb: "681", naiyou: "左第1指骨複骨折", tanshuku: "左複骨折" },
    { code: 682, jrdb: "682", naiyou: "左前深管骨瘤", tanshuku: "左前骨瘤" },
    { code: 683, jrdb: "683", naiyou: "右第3中手骨々折", tanshuku: "右手骨折" },
    { code: 684, jrdb: "684", naiyou: "右後肢蹴傷", tanshuku: "右後蹴傷" },
    { code: 685, jrdb: "685", naiyou: "左前腕部打撲傷", tanshuku: "左腕打撲" },
    { code: 686, jrdb: "686", naiyou: "左結膜炎", tanshuku: "左結膜炎" },
    { code: 687, jrdb: "687", naiyou: "右腕節炎", tanshuku: "右腕節炎" },
    { code: 688, jrdb: "688", naiyou: "右後肢裂創", tanshuku: "右後裂創" },
    { code: 689, jrdb: "689", naiyou: "右膝蓋部蹴傷", tanshuku: "右膝蹴傷" },
    { code: 690, jrdb: "690", naiyou: "頭部打撲症", tanshuku: "頭部打撲" },
    { code: 691, jrdb: "691", naiyou: "左後球節部挫創", tanshuku: "左球挫創" },
    { code: 692, jrdb: "692", naiyou: "左第1趾骨々折", tanshuku: "左趾骨折" },
    { code: 693, jrdb: "693", naiyou: "左第1指節種子骨複骨", tanshuku: "左種子折" },
    { code: 694, jrdb: "694", naiyou: "口内炎", tanshuku: "口内炎" },
    { code: 695, jrdb: "695", naiyou: "鼻部挫創", tanshuku: "鼻部挫創" },
    { code: 696, jrdb: "696", naiyou: "左肋部蹴傷", tanshuku: "左肋蹴傷" },
    { code: 697, jrdb: "697", naiyou: "左前管部挫創", tanshuku: "左管挫創" },
    { code: 698, jrdb: "698", naiyou: "左腰部挫創", tanshuku: "左腰挫創" },
    { code: 699, jrdb: "699", naiyou: "乳房炎", tanshuku: "乳房炎" },
    { code: 700, jrdb: "700", naiyou: "シャド2走目", tanshuku: "鼻2走目" },
    { code: 701, jrdb: "701", naiyou: "シャド3走目", tanshuku: "鼻3走目" },
    { code: 702, jrdb: "702", naiyou: "ブリ逆効果", tanshuku: "ブ逆効果" },
    { code: 703, jrdb: "703", naiyou: "発進不良", tanshuku: "発進不良" },
    { code: 704, jrdb: "704", naiyou: "つかみどころない", tanshuku: "つかめぬ" },
    { code: 705, jrdb: "705", naiyou: "内側に逃避", tanshuku: "内側逃避" },
    { code: 706, jrdb: "706", naiyou: "外側に逃避", tanshuku: "外側逃避" },
    { code: 707, jrdb: "707", naiyou: "フットワーク○", tanshuku: "脚捌き○" },
    { code: 708, jrdb: "708", naiyou: "落馬再騎乗", tanshuku: "落馬再乗" },
    { code: 709, jrdb: "709", naiyou: "トモ傷める(ゲート内)", tanshuku: "ゲ内ト傷" },
    { code: 710, jrdb: "710", naiyou: "障害練習効果", tanshuku: "障練習効" },
    { code: 711, jrdb: "711", naiyou: "空馬影響", tanshuku: "空馬影響" },
    { code: 712, jrdb: "712", naiyou: "馬体検査", tanshuku: "馬体検査" },
    { code: 713, jrdb: "713", naiyou: "今回蹄鉄替○", tanshuku: "今蹄鉄○" },
    { code: 714, jrdb: "714", naiyou: "今回蹄鉄替×", tanshuku: "今蹄鉄×" },
    { code: 715, jrdb: "715", naiyou: "バドック放馬", tanshuku: "パド放馬" },
    { code: 716, jrdb: "716", naiyou: "発進不良", tanshuku: "発進不良" },
    { code: 717, jrdb: "717", naiyou: "ステッキ×", tanshuku: "ムチ×" },
    { code: 718, jrdb: "718", naiyou: "道中外々", tanshuku: "道中外々" },
    { code: 719, jrdb: "719", naiyou: "雨○", tanshuku: "雨○" },
    { code: 720, jrdb: "720", naiyou: "雨×", tanshuku: "雨×" },
    { code: 721, jrdb: "721", naiyou: "スタート芝○", tanshuku: "スタ芝○" },
    { code: 722, jrdb: "722", naiyou: "勝負所モタつく", tanshuku: "勝負モタ" },
    { code: 723, jrdb: "723", naiyou: "適距離", tanshuku: "適距離" },
    { code: 724, jrdb: "724", naiyou: "ゲート練習", tanshuku: "ゲート練" },
    { code: 725, jrdb: "725", naiyou: "障害練習", tanshuku: "障害練習" },
    { code: 726, jrdb: "726", naiyou: "中間鞍傷", tanshuku: "中間鞍傷" },
    { code: 727, jrdb: "727", naiyou: "次走オッズチェック", tanshuku: "次ＯＺチ" },
    { code: 728, jrdb: "728", naiyou: "時計速○", tanshuku: "時計速○" },
    { code: 729, jrdb: "729", naiyou: "時計速×", tanshuku: "時計速×" },
    { code: 730, jrdb: "730", naiyou: "脚使処難", tanshuku: "脚使処難" },
    { code: 731, jrdb: "731", naiyou: "根性なし", tanshuku: "根性なし" },
    { code: 732, jrdb: "732", naiyou: "レース振スムーズ", tanshuku: "R振スム" },
    { code: 733, jrdb: "733", naiyou: "一本調子", tanshuku: "一本調子" },
    { code: 734, jrdb: "734", naiyou: "完歩小さい", tanshuku: "完歩小さ" },
    { code: 735, jrdb: "735", naiyou: "芝ダOK", tanshuku: "芝ダOK" },
    { code: 736, jrdb: "736", naiyou: "スムーズさ欠", tanshuku: "スム欠く" },
    { code: 737, jrdb: "737", naiyou: "生ズルイ", tanshuku: "生ズルイ" },
    { code: 738, jrdb: "738", naiyou: "絞れれば", tanshuku: "絞れれば" },
    { code: 739, jrdb: "739", naiyou: "水浮ダ○", tanshuku: "水浮ダ○" },
    { code: 740, jrdb: "740", naiyou: "追いかけられる○", tanshuku: "追れる○" },
    { code: 741, jrdb: "741", naiyou: "口出血", tanshuku: "口出血" },
    { code: 742, jrdb: "742", naiyou: "馬装整備", tanshuku: "馬装整備" },
    { code: 743, jrdb: "743", naiyou: "芝ダ切れ目飛ぶ", tanshuku: "芝ダ切飛" },
    { code: 744, jrdb: "744", naiyou: "中間外傷", tanshuku: "中間外傷" },
    { code: 745, jrdb: "745", naiyou: "中間感冒", tanshuku: "中間感冒" },
    { code: 746, jrdb: "746", naiyou: "中間抜歯", tanshuku: "中間抜歯" },
    { code: 747, jrdb: "747", naiyou: "調教不足", tanshuku: "調教不足" },
    { code: 748, jrdb: "748", naiyou: "歯替わり", tanshuku: "歯替わり" },
    { code: 749, jrdb: "749", naiyou: "馬場入り1番早い", tanshuku: "返馬先入" },
    { code: 750, jrdb: "750", naiyou: "Pブリンカー効果あり", tanshuku: "P効果○" },
    { code: 751, jrdb: "751", naiyou: "舌くくり効果あり", tanshuku: "舌効果○" },
    { code: 752, jrdb: "752", naiyou: "ノーズバンド効果あり", tanshuku: "N効果○" },
    { code: 753, jrdb: "753", naiyou: "鼻逆効果", tanshuku: "鼻逆効果" },
    { code: 754, jrdb: "754", naiyou: "舌くくりで出血", tanshuku: "舌括出血" },
    { code: 755, jrdb: "755", naiyou: "ハミで口切る", tanshuku: "ハミ口切" },
    { code: 756, jrdb: "756", naiyou: "馬場入り前蹄鉄打ち直", tanshuku: "馬入鉄打" },
    { code: 757, jrdb: "757", naiyou: "ハミ替え", tanshuku: "ハミ替え" },
    { code: 758, jrdb: "758", naiyou: "馬具変更", tanshuku: "馬具変更" },
    { code: 759, jrdb: "759", naiyou: "ハミ替え逆効果", tanshuku: "ハ替逆効" },
    { code: 760, jrdb: "760", naiyou: "転厩", tanshuku: "転厩" },
    { code: 761, jrdb: "761", naiyou: "厩務員替り", tanshuku: "厩務員替" },
    { code: 762, jrdb: "762", naiyou: "腰疲れ", tanshuku: "腰疲れ" },
    { code: 763, jrdb: "763", naiyou: "口硬い", tanshuku: "口硬い" },
    { code: 764, jrdb: "764", naiyou: "返し馬気合乗りすぎ", tanshuku: "返気乗過" },
    { code: 765, jrdb: "765", naiyou: "口開けたまま走る", tanshuku: "口開け走" },
    { code: 766, jrdb: "766", naiyou: "パドック後出し", tanshuku: "パド後出" },
    { code: 767, jrdb: "767", naiyou: "返し馬後出し", tanshuku: "返馬後出" },
    { code: 768, jrdb: "768", naiyou: "ハミ効かず", tanshuku: "ハミ効ず" },
    { code: 769, jrdb: "769", naiyou: "もたれる", tanshuku: "もたれる" },
    { code: 770, jrdb: "770", naiyou: "頭上げる", tanshuku: "頭上げる" },
    { code: 771, jrdb: "771", naiyou: "ブリンカー必要", tanshuku: "B必要" },
    { code: 772, jrdb: "772", naiyou: "フラフラ", tanshuku: "フラフラ" },
    { code: 773, jrdb: "773", naiyou: "芝切れ目気にする", tanshuku: "芝切気に" },
    { code: 774, jrdb: "774", naiyou: "芝切れ目躓く", tanshuku: "芝切躓く" },
    { code: 775, jrdb: "775", naiyou: "脚部不安", tanshuku: "脚部不安" },
    { code: 779, jrdb: "779", naiyou: "再ゲートやる気失う", tanshuku: "再ゲ気失" },
    { code: 780, jrdb: "780", naiyou: "攻め駆けする", tanshuku: "攻め駆け" },
    { code: 781, jrdb: "781", naiyou: "直線追うのやめる", tanshuku: "直追止め" },
    { code: 782, jrdb: "782", naiyou: "異常歩様", tanshuku: "異常歩様" },
    { code: 783, jrdb: "783", naiyou: "針立て直し効果○", tanshuku: "針立直○" },
    { code: 784, jrdb: "784", naiyou: "ムキになって走る", tanshuku: "ムキ走る" },
    { code: 785, jrdb: "785", naiyou: "仕掛け遅れる", tanshuku: "仕掛け遅" },
    { code: 786, jrdb: "786", naiyou: "手綱切れる", tanshuku: "手綱切れ" },
    { code: 787, jrdb: "787", naiyou: "ゴチャつく", tanshuku: "ゴチャ" },
    { code: 789, jrdb: "789", naiyou: "併せる形○", tanshuku: "併せ形○" },
    { code: 790, jrdb: "790", naiyou: "ハミ敏感", tanshuku: "ハミ敏感" },
    { code: 791, jrdb: "791", naiyou: "トビ綺麗", tanshuku: "トビ綺麗" },
    { code: 792, jrdb: "792", naiyou: "硬い馬場○", tanshuku: "硬馬場○" },
    { code: 793, jrdb: "793", naiyou: "硬い馬場×", tanshuku: "硬馬場×" },
    { code: 794, jrdb: "794", naiyou: "調教注意（戒告）", tanshuku: "戒告調教" },
    { code: 795, jrdb: "795", naiyou: "脚抜きいいダ○", tanshuku: "脚抜ダ○" },
    { code: 796, jrdb: "796", naiyou: "脚抜きいいダ×", tanshuku: "脚抜ダ×" },
    { code: 797, jrdb: "797", naiyou: "乾いたダ○", tanshuku: "乾ダ○" },
    { code: 798, jrdb: "798", naiyou: "乾いたダ×", tanshuku: "乾ダ×" },
    { code: 799, jrdb: "799", naiyou: "中間フレグモーネ", tanshuku: "中フレグ" },
    { code: 800, jrdb: "800", naiyou: "ソエ良化", tanshuku: "ソエ良化" },
    { code: 801, jrdb: "801", naiyou: "馬場入場後再検量", tanshuku: "馬入再検" },
    { code: 802, jrdb: "802", naiyou: "多頭数○", tanshuku: "多頭数○" },
    { code: 803, jrdb: "803", naiyou: "耳立てる", tanshuku: "耳立てる" },
    { code: 804, jrdb: "804", naiyou: "直線余力あり", tanshuku: "直余力有" },
    { code: 805, jrdb: "805", naiyou: "ゲート入り嫌がる", tanshuku: "ゲ入り嫌" },
    { code: 806, jrdb: "806", naiyou: "ヨレる", tanshuku: "ヨレる" },
    { code: 807, jrdb: "807", naiyou: "併せる形×", tanshuku: "併せる×" },
    { code: 808, jrdb: "808", naiyou: "右回り△", tanshuku: "右回り△" },
    { code: 809, jrdb: "809", naiyou: "荒れ馬場○", tanshuku: "荒馬場○" },
    { code: 810, jrdb: "810", naiyou: "荒れ馬場△", tanshuku: "荒馬場△" },
    { code: 811, jrdb: "811", naiyou: "荒れ馬場×", tanshuku: "荒馬場×" },
    { code: 812, jrdb: "812", naiyou: "ハナこだわらず", tanshuku: "ハナ拘ず" },
    { code: 813, jrdb: "813", naiyou: "スタート抜群", tanshuku: "スタ抜群" },
    { code: 814, jrdb: "814", naiyou: "蹄鉄ずれる", tanshuku: "蹄鉄ズレ" },
    { code: 815, jrdb: "815", naiyou: "レース直前ボロ", tanshuku: "R前ボロ" },
    { code: 816, jrdb: "816", naiyou: "仕掛け早い", tanshuku: "仕掛早い" },
    { code: 817, jrdb: "817", naiyou: "馬場良い所通る", tanshuku: "馬場良通" },
    { code: 818, jrdb: "818", naiyou: "馬場悪い所通る", tanshuku: "馬場悪通" },
    { code: 819, jrdb: "819", naiyou: "展開厳しい", tanshuku: "展開厳い" },
    { code: 820, jrdb: "820", naiyou: "展開恵まれ", tanshuku: "展開恵れ" },
    { code: 821, jrdb: "821", naiyou: "不正駆歩", tanshuku: "不正駆歩" },
    { code: 822, jrdb: "822", naiyou: "濡れたダ○", tanshuku: "濡れダ○" },
    { code: 823, jrdb: "823", naiyou: "返し馬落馬", tanshuku: "返馬落馬" },
    { code: 824, jrdb: "824", naiyou: "暖かくなってくる○", tanshuku: "暖かく○" },
    { code: 825, jrdb: "825", naiyou: "水浮くダ×", tanshuku: "水浮ダ×" },
    { code: 826, jrdb: "826", naiyou: "パドック先頭", tanshuku: "パド先頭" },
    { code: 827, jrdb: "827", naiyou: "返し馬スムーズ", tanshuku: "返馬スム" },
    { code: 828, jrdb: "828", naiyou: "返し馬逆方向へ", tanshuku: "返馬逆へ" },
    { code: 829, jrdb: "829", naiyou: "パドック尻尾振る", tanshuku: "パ尾振る" },
    { code: 830, jrdb: "830", naiyou: "制御が乱暴", tanshuku: "制御乱暴" },
    { code: 831, jrdb: "831", naiyou: "濡れたダ×", tanshuku: "濡れダ×" },
    { code: 832, jrdb: "832", naiyou: "パドック立ち上がる", tanshuku: "パド立上" },
    { code: 833, jrdb: "833", naiyou: "パドック舌出す", tanshuku: "パド舌出" },
    { code: 834, jrdb: "834", naiyou: "返し馬気合つける", tanshuku: "返馬気合" },
    { code: 835, jrdb: "835", naiyou: "返し馬元気", tanshuku: "返馬元気" },
    { code: 836, jrdb: "836", naiyou: "返し馬のびのび", tanshuku: "返のびの" },
    { code: 837, jrdb: "837", naiyou: "返し馬口割る", tanshuku: "返口割る" },
    { code: 838, jrdb: "838", naiyou: "返し馬掛かる", tanshuku: "返掛かる" },
    { code: 839, jrdb: "839", naiyou: "返し馬舌越す", tanshuku: "返馬舌越" },
    { code: 840, jrdb: "840", naiyou: "ハミ気にする", tanshuku: "ハミ気に" },
    { code: 841, jrdb: "841", naiyou: "尻尾短い", tanshuku: "尻尾短い" },
    { code: 842, jrdb: "842", naiyou: "尻っ跳ね", tanshuku: "尻っ跳ね" },
    { code: 843, jrdb: "843", naiyou: "あくび", tanshuku: "あくび" },
    { code: 844, jrdb: "844", naiyou: "馬場入り嫌がる", tanshuku: "馬場入嫌" },
    { code: 845, jrdb: "845", naiyou: "厩務員に引かれて歩く", tanshuku: "厩務引歩" },
    { code: 846, jrdb: "846", naiyou: "パドックハミ気にする", tanshuku: "Pハミ気" },
    { code: 847, jrdb: "847", naiyou: "軟らかい芝×", tanshuku: "軟ら芝×" },
    { code: 848, jrdb: "848", naiyou: "背ったる", tanshuku: "背ったる" },
    { code: 849, jrdb: "849", naiyou: "馬場入場後騎乗", tanshuku: "馬入騎乗" },
    { code: 850, jrdb: "850", naiyou: "返し馬立ち上がる", tanshuku: "返馬立上" },
    { code: 851, jrdb: "851", naiyou: "返し馬尻っぱね", tanshuku: "返馬尻跳" },
    { code: 852, jrdb: "852", naiyou: "パドック外側から馬引", tanshuku: "P外馬引" },
    { code: 853, jrdb: "853", naiyou: "レースセンス抜群", tanshuku: "センス◎" },
    { code: 854, jrdb: "854", naiyou: "蛇行", tanshuku: "蛇行" },
    { code: 855, jrdb: "855", naiyou: "(名パド)文字気にする", tanshuku: "パ文字気" },
    { code: 856, jrdb: "856", naiyou: "厩務員に甘える", tanshuku: "厩務員甘" },
    { code: 857, jrdb: "857", naiyou: "返し馬軽目", tanshuku: "返馬軽目" },
    { code: 858, jrdb: "858", naiyou: "返し馬抑える", tanshuku: "返馬抑え" },
    { code: 859, jrdb: "859", naiyou: "器官疾患", tanshuku: "▽▽▽" },
    { code: 860, jrdb: "860", naiyou: "返し馬怒る", tanshuku: "返馬怒る" },
    { code: 861, jrdb: "861", naiyou: "パドック柵蹴る", tanshuku: "パ柵蹴る" },
    { code: 862, jrdb: "862", naiyou: "パドック機嫌良し", tanshuku: "機嫌良し" },
    { code: 863, jrdb: "863", naiyou: "パドック口出血", tanshuku: "パ口出血" },
    { code: 864, jrdb: "864", naiyou: "返し馬気負う", tanshuku: "返気負う" },
    { code: 865, jrdb: "865", naiyou: "パドック耳動かす", tanshuku: "パ耳動す" },
    { code: 866, jrdb: "866", naiyou: "返し馬やる気", tanshuku: "返やる気" },
    { code: 867, jrdb: "867", naiyou: "返し馬しっかり", tanshuku: "返しっか" },
    { code: 868, jrdb: "868", naiyou: "返し馬バネ利いた動き", tanshuku: "返バネ" },
    { code: 869, jrdb: "869", naiyou: "緩急苦手", tanshuku: "緩急苦手" },
    { code: 870, jrdb: "870", naiyou: "高速馬場○", tanshuku: "高速場○" },
    { code: 871, jrdb: "871", naiyou: "高速馬場×", tanshuku: "高速場×" },
    { code: 872, jrdb: "872", naiyou: "上がり速い○", tanshuku: "上が速○" },
    { code: 873, jrdb: "873", naiyou: "上がり速い×", tanshuku: "上が速×" },
    { code: 874, jrdb: "874", naiyou: "上がり掛かる○", tanshuku: "上が掛○" },
    { code: 875, jrdb: "875", naiyou: "上がり掛かる×", tanshuku: "上が掛×" },
    { code: 876, jrdb: "876", naiyou: "直線挟まる", tanshuku: "直線挟る" },
    { code: 877, jrdb: "877", naiyou: "新潟外回り向き", tanshuku: "新潟外向" },
    { code: 878, jrdb: "878", naiyou: "新潟内回り向き", tanshuku: "新潟内向" },
    { code: 879, jrdb: "879", naiyou: "競走中止", tanshuku: "競走中止" },
    { code: 880, jrdb: "880", naiyou: "完勝", tanshuku: "完勝" },
    { code: 881, jrdb: "881", naiyou: "距離○", tanshuku: "距離○" },
    { code: 882, jrdb: "882", naiyou: "展開向かず", tanshuku: "展開不向" },
    { code: 883, jrdb: "883", naiyou: "追って案外", tanshuku: "追って×" },
    { code: 884, jrdb: "884", naiyou: "4角一杯", tanshuku: "4角一杯" },
    { code: 885, jrdb: "885", naiyou: "出ムチ入る", tanshuku: "出ムチ" },
    { code: 886, jrdb: "886", naiyou: "展開向く", tanshuku: "展開向く" },
    { code: 887, jrdb: "887", naiyou: "二の脚速い", tanshuku: "二脚速い" },
    { code: 888, jrdb: "888", naiyou: "後ろから行くとダメ", tanshuku: "後行く×" },
    { code: 889, jrdb: "889", naiyou: "前に行く○", tanshuku: "前行く○" },
    { code: 890, jrdb: "890", naiyou: "後ろから行く○", tanshuku: "後行く○" },
    { code: 901, jrdb: "901", naiyou: "左第1趾骨粉砕骨折", tanshuku: "左粉骨折" },
    { code: 902, jrdb: "902", naiyou: "右第1趾骨粉砕骨折", tanshuku: "右粉骨折" },
    { code: 903, jrdb: "903", naiyou: "左中手骨開放骨折", tanshuku: "左開骨折" },
    { code: 904, jrdb: "904", naiyou: "右第3中手骨複骨折", tanshuku: "右複骨折" },
    { code: 905, jrdb: "905", naiyou: "右第1指骨粉砕骨折", tanshuku: "右粉骨折" },
    { code: 906, jrdb: "906", naiyou: "左第1指骨開放骨折", tanshuku: "左開骨折" },
    { code: 907, jrdb: "907", naiyou: "右第3中手骨開放骨折", tanshuku: "右開脱臼" },
    { code: 908, jrdb: "908", naiyou: "左第1指関節開放脱臼", tanshuku: "左開脱臼" },
    { code: 909, jrdb: "909", naiyou: "左下腿骨粉砕骨折", tanshuku: "左粉骨折" },
    { code: 910, jrdb: "910", naiyou: "左第1指節種子骨粉砕", tanshuku: "左粉骨折" },
    { code: 911, jrdb: "911", naiyou: "右第3中手骨罅裂骨折", tanshuku: "罅裂骨折" },
    { code: 912, jrdb: "912", naiyou: "左手根骨粉砕骨折", tanshuku: "左粉骨折" },
    { code: 913, jrdb: "913", naiyou: "右第1指骨開放骨折", tanshuku: "右開骨折" },
    { code: 914, jrdb: "914", naiyou: "心不全", tanshuku: "心不全" },
    { code: 915, jrdb: "915", naiyou: "左第3中手骨粉砕骨折", tanshuku: "左粉骨折" },
    { code: 916, jrdb: "916", naiyou: "右下腿骨開放骨折", tanshuku: "右開骨折" },
    { code: 917, jrdb: "917", naiyou: "右中足骨開放骨折", tanshuku: "右開骨折" },
    { code: 918, jrdb: "918", naiyou: "右第1指骨複骨折", tanshuku: "右複骨折" },
    { code: 919, jrdb: "919", naiyou: "右第1指関節脱臼", tanshuku: "右関脱臼" },
    { code: 920, jrdb: "920", naiyou: "右第1指関節開放性脱", tanshuku: "右開脱臼" },
    { code: 921, jrdb: "921", naiyou: "左第3手根骨複骨折", tanshuku: "左指骨折" },
    { code: 922, jrdb: "922", naiyou: "左第1指関節開放性脱", tanshuku: "左開脱臼" },
    { code: 923, jrdb: "923", naiyou: "左第3中手骨開放骨折", tanshuku: "左開骨折" },
    { code: 924, jrdb: "924", naiyou: "右前種子骨靱帯断裂", tanshuku: "右靱断裂" },
    { code: 925, jrdb: "925", naiyou: "両第1指関節開放性脱", tanshuku: "両指脱臼" },
    { code: 926, jrdb: "926", naiyou: "右前繋靭帯不全断裂", tanshuku: "右繋不裂" },
    { code: 927, jrdb: "927", naiyou: "歯ぎしり（パドック）", tanshuku: "歯ぎしり" },
    { code: 928, jrdb: "928", naiyou: "レース後口出血", tanshuku: "口出血" },
    { code: 929, jrdb: "929", naiyou: "騎乗してパドック周回", tanshuku: "騎乗周回" },
    { code: 930, jrdb: "930", naiyou: "喉不安", tanshuku: "喉不安" },
    { code: 931, jrdb: "931", naiyou: "右手根骨粉砕骨折", tanshuku: "右粉骨折" },
    { code: 932, jrdb: "932", naiyou: "両前浅屈腱不全断裂", tanshuku: "両浅不裂" },
    { code: 933, jrdb: "933", naiyou: "両後繋靭帯不全断裂", tanshuku: "両繋不裂" },
    { code: 934, jrdb: "934", naiyou: "両後管部挫創", tanshuku: "両管挫創" },
    { code: 935, jrdb: "935", naiyou: "腹部挫創", tanshuku: "腹部挫創" },
    { code: 936, jrdb: "936", naiyou: "鼻梁部挫創", tanshuku: "鼻梁挫創" },
    { code: 937, jrdb: "937", naiyou: "背部挫創", tanshuku: "背部挫創" },
    { code: 938, jrdb: "938", naiyou: "頭部打撲傷", tanshuku: "頭部打撲" },
    { code: 939, jrdb: "939", naiyou: "頭部挫傷", tanshuku: "頭部挫傷" },
    { code: 940, jrdb: "940", naiyou: "頭部外傷", tanshuku: "頭部外傷" },
    { code: 941, jrdb: "941", naiyou: "舌部裂創", tanshuku: "舌部裂創" },
    { code: 942, jrdb: "942", naiyou: "肺充血", tanshuku: "肺充血" },
    { code: 943, jrdb: "943", naiyou: "右第1指節種子骨粉砕", tanshuku: "左粉骨折" },
    { code: 944, jrdb: "944", naiyou: "右腸骨々折", tanshuku: "右腸骨折" },
  ]
);
